- TramsDataApi.Test/Controllers/TrustsControllerTests.cs
- TramsDataApi.Test/DbFixture.cs
- TramsDataApi.Test/Integration/HealthCheckIntegrationTests.cs
- TramsDataApi.Test/Integration/TrustsIntegrationTests.cs
- TramsDataApi.Test/TramsDataApi.Test.csproj
- TramsDataApi/Controllers/TrustsController.cs
- TramsDataApi/Gateways/ITrustGateway.cs
- TramsDataApi/Gateways/TrustGateway.cs
- TramsDataApi/Startup.cs
* Adds a Gateway wrapper around the DB context
* Renames controller tests to integration tests
* Adds unit tests for TrustsController
> Move database to gateway

- TramsDataApi.Test/Controllers/AcademyTransferProjectsControllerTests.cs
- TramsDataApi.Test/Factories/AcademyTransferProjectFactoryTests.cs
- TramsDataApi.Test/Factories/AcademyTransferProjectResponseFactoryTests.cs
- TramsDataApi.Test/Integration/AcademyTransferProjectIntegrationTests.cs
- TramsDataApi.Test/UseCases/CreateAcademyTransferProjectTests.cs
- TramsDataApi.Test/UseCases/GetAcademyTransferProjectTests.cs
- TramsDataApi.Test/UseCases/UpdateAcademyTransferProjectTests.cs
- TramsDataApi/Controllers/AcademyTransferProjectController.cs
- TramsDataApi/Factories/AcademyTransferProjectFactory.cs
- TramsDataApi/Factories/AcademyTransferProjectResponseFactory.cs
- TramsDataApi/Gateways/AcademyTransferProjectGateway.cs
- TramsDataApi/Gateways/IAcademyTransferProjectGateway.cs
- TramsDataApi/Startup.cs
- TramsDataApi/UseCases/CreateAcademyTransferProject.cs
- TramsDataApi/UseCases/GetAcademyTransferProject.cs
- TramsDataApi/UseCases/IGetAcademyTransferProject.cs
- TramsDataApi/UseCases/IUpdateAcademyTransferProject.cs
- TramsDataApi/UseCases/UpdateAcademyTransferProject.cs
This PR Adds the PATCH route for updating a Academy Transfer Project.
> Patch academy transfer project

- TramsDataApi.Test/Controllers/AcademyTransferProjectsControllerTests.cs
- TramsDataApi.Test/Integration/AcademyTransferProjectIntegrationTests.cs
- TramsDataApi.Test/UseCases/IndexAcademyTransferProjectTests.cs
- TramsDataApi/Controllers/AcademyTransferProjectController.cs
- TramsDataApi/Gateways/AcademyTransferProjectGateway.cs
- TramsDataApi/Gateways/IAcademyTransferProjectGateway.cs
- TramsDataApi/ResponseModels/AcademyTransferProjectSummaryResponse.cs
- TramsDataApi/Startup.cs
- TramsDataApi/UseCases/IIndexAcademyTransferProjects.cs
- TramsDataApi/UseCases/IndexAcademyTransferProjects.cs
- TramsDataApi/appsettings.json
Adds the GET index route for Academy Transfer Projects. 
Adds pagination to the results
> Index academy transfer projects route

- TramsDataApi.Test/Factories/AcademyConversionProjectFactoryTests.cs
- TramsDataApi.Test/Integration/AcademyConversionProjectsIntegrationTests.cs
- TramsDataApi/Controllers/AcademyConversionProjectController.cs
- TramsDataApi/Factories/AcademyConversionProjectFactory.cs
- TramsDataApi/RequestModels/AcademyConversionProject/GetAcademyConversionProjectByIdRequest.cs
- TramsDataApi/RequestModels/AcademyConversionProject/GetAllAcademyConversionProjectsRequest.cs
- TramsDataApi/RequestModels/AcademyConversionProject/UpdateAcademyConversionProjectRequest.cs
- TramsDataApi/ResponseModels/AcademyConversionProject/UpdateAcademyConversionProjectResponse.cs
- TramsDataApi/Startup.cs
- TramsDataApi/UseCases/GetAcademyConversionProjects.cs
- TramsDataApi/UseCases/IUpdateAcademyConversionProject.cs
- TramsDataApi/UseCases/UpdateAcademyConversionProject.cs
Adds new patch endpoint to update an academy conversion project
> Update academy conversion project

- TramsDataApi.Test/Factories/AcademyConversionProjectFactoryTests.cs
- TramsDataApi.Test/Factories/AcademyConversionProjectResponseFactoryTests.cs
- TramsDataApi/Factories/AcademyConversionProjectFactory.cs
- TramsDataApi/Factories/AcademyConversionProjectResponseFactory.cs
Map Local Authority Information Template fields when updating and getting Academy Conversion projects.
> Map Local Authority Information Template fields

- TramsDataApi.Test/Factories/AcademyConversionProjectFactoryTests.cs
- TramsDataApi.Test/Factories/AcademyConversionProjectResponseFactoryTests.cs
- TramsDataApi.Test/Integration/AcademyConversionProjectsIntegrationTests.cs
- TramsDataApi/Factories/AcademyConversionProjectFactory.cs
- TramsDataApi/Factories/AcademyConversionProjectResponseFactory.cs
- Added request and response mapping for risks and issues
- Added tests
> A2B: Risks and issues

- TramsDataApi.Test/Factories/AcademyTransferProjectFactoryTests.cs
- TramsDataApi.Test/Factories/AcademyTransferProjectResponseFactoryTests.cs
- TramsDataApi/DatabaseModels/AcademyTransferProjects.cs
- TramsDataApi/Factories/AcademyTransferProjectFactory.cs
- TramsDataApi/Factories/AcademyTransferProjectResponseFactory.cs
- TramsDataApi/Migrations/TramsDb/20210629095534_at-general-information.Designer.cs
- TramsDataApi/Migrations/TramsDb/20210629095534_at-general-information.cs
- TramsDataApi/RequestModels/AcademyTransferProjectRequest.cs
- TramsDataApi/ResponseModels/AcademyTransferProjectResponse.cs
Add author and recommendation fields to support the academy transfers general information page
> Add AT general information author and recommendation fields

- TramsDataApi.Test/Factories/KeyStage2ResponseFactoryTests.cs
- TramsDataApi.Test/Integration/EducationPerformanceIntegrationTests.cs
- TramsDataApi.Test/UseCases/GetKeyStagePerformanceByUrnTests.cs
- TramsDataApi/Factories/EducationPerformanceFactories/KeyStage2PerformanceResponseFactory.cs
- TramsDataApi/ResponseModels/EducationalPerformance/KeyStage2PerformanceResponse.cs
- TramsDataApi/UseCases/GetKeyStagePerformanceByUrn.cs
The PR adds national average data for the key stage 2 data for the AT team.
> Add national average data to key stage 2

- TramsDataApi.Test/Factories/KeyStage2ResponseFactoryTests.cs
- TramsDataApi.Test/Factories/KeyStage4ResponseFactoryTests.cs
- TramsDataApi.Test/Integration/EducationPerformanceIntegrationTests.cs
- TramsDataApi.Test/UseCases/GetKeyStagePerformanceByUrnTests.cs
- TramsDataApi/Factories/EducationPerformanceFactories/GroupedEducationPerformanceFactory.cs
- TramsDataApi/Factories/EducationPerformanceFactories/KeyStage2PerformanceResponseFactory.cs
- TramsDataApi/Factories/EducationPerformanceFactories/KeyStage4PerformanceResponseFactory.cs
- TramsDataApi/Gateways/EducationPerformanceGateway.cs
- TramsDataApi/Gateways/IEducationPerformanceGateway.cs
- TramsDataApi/ResponseModels/EducationalPerformance/KeyStage2PerformanceResponse.cs
- TramsDataApi/ResponseModels/EducationalPerformance/KeyStage4PerformanceResponse.cs
- TramsDataApi/UseCases/GetKeyStagePerformanceByUrn.cs
This PR adds some missing national and local authority average data to key stage 2 and 4 responses
> Add national and local authority data

- TramsDataApi.Test/Factories/AcademyTransferProjectFactoryTests.cs
- TramsDataApi.Test/Factories/AcademyTransferProjectResponseFactoryTests.cs
- TramsDataApi/DatabaseModels/AcademyTransferProjects.cs
- TramsDataApi/Factories/AcademyTransferProjectFactory.cs
- TramsDataApi/Factories/AcademyTransferProjectResponseFactory.cs
- TramsDataApi/Migrations/TramsDb/20210709120813_AT-additional-information.Designer.cs
- TramsDataApi/Migrations/TramsDb/20210709120813_AT-additional-information.cs
- TramsDataApi/RequestModels/AcademyTransferProjectRequest.cs
- TramsDataApi/ResponseModels/AcademyTransferProjectResponse.cs
Add the additional information fields for Academy Transfers project
> Add AT additional information fields

- TramsDataApi.ApplyToBecome/SyncAcademyConversionProjectFactory.cs
- TramsDataApi.Test/ApplyToBecome/SyncAcademyConversionProjectFactoryTests.cs
Correct mapping of ACP application received date when syncing IfdPipeline entity to ACP table.
> Correct mapping of ACP application received date

- TramsDataApi.Test/Utils/Generators.cs
- TramsDataApi/Gateways/EstablishmentGateway.cs
Update to use the academy Urn when getting academy conversion data
> Amend academy conversion data to use GeneralDetailsAcademyUrn

- TramsDataApi.Test/Utils/Generators.cs
- TramsDataApi/Gateways/EstablishmentGateway.cs
After some investigation there is a problem with the PK of the vw_AC table, this needs further looking into so reverting back for now
> Revert view academy conversions urn

- TramsDataApi.Test/Utils/Generators.cs
- TramsDataApi/DatabaseModels/LegacyTramsDbContext.ViewAcademyConversions.cs
- TramsDataApi/Gateways/EstablishmentGateway.cs
This is fix to an issue where ifd.vw_AC table was causing error due to null primary key column
> Fix to academy performance data

- .github/workflows/main_trams-external-api.yml
- TramsDataApi.Test/Controllers/AcademyTransferProjectsControllerTests.cs
- TramsDataApi.Test/Controllers/EducationPerformanceControllerTests.cs
- TramsDataApi.Test/Controllers/EstablishmentsControllerTests.cs
- TramsDataApi.Test/Controllers/TrustsControllerTests.cs
- TramsDataApi.Test/Integration/AcademyConversionProjectNotesIntegrationTests.cs
- TramsDataApi/Controllers/AcademyConversionProjectController.cs
- TramsDataApi/Controllers/AcademyConversionProjectNotesController.cs
- TramsDataApi/Controllers/AcademyTransferProjectController.cs
- TramsDataApi/Controllers/EstablishmentsController.cs
- TramsDataApi/Controllers/HealthCheckController.cs
- TramsDataApi/Controllers/KeyStagePerformanceController.cs
- TramsDataApi/Controllers/TrustsController.cs
- TramsDataApi/Middleware/ExceptionHandlerMiddleware.cs
- TramsDataApi/Program.cs
- TramsDataApi/ResponseModels/ErrorResponse.cs
- TramsDataApi/Startup.cs
- TramsDataApi/TramsDataApi.csproj
Reverts DFE-Digital/trams-data-api#80
> Revert "Revert "Add logging""

- TramsDataApi.Test/Factories/AcademyConversionProjectFactoryTests.cs
- TramsDataApi.Test/Factories/AcademyConversionProjectResponseFactoryTests.cs
- TramsDataApi.Test/Integration/AcademyConversionProjectsIntegrationTests.cs
- TramsDataApi/DatabaseModels/AcademyConversionProject.cs
- TramsDataApi/Factories/AcademyConversionProjectFactory.cs
- TramsDataApi/Factories/AcademyConversionProjectResponseFactory.cs
- TramsDataApi/Factories/EducationPerformanceFactories/KeyStage5PerformanceResponseFactory.cs
- TramsDataApi/Migrations/TramsDb/20210811092834_AddKS5AdditionalInfoToACP.Designer.cs
- TramsDataApi/Migrations/TramsDb/20210811092834_AddKS5AdditionalInfoToACP.cs
- TramsDataApi/RequestModels/AcademyConversionProject/UpdateAcademyConversionProjectRequest.cs
- TramsDataApi/ResponseModels/AcademyConversionProject/AcademyConversionProjectResponse.cs
- Add KS5 additional info field to ACP table
- Map KS5 additional info field when retrieving and updating ACP
> KS5 additional info

- TramsDataApi.Test/Controllers/AcademyConversionProjectsControllerV2Tests.cs
- TramsDataApi.Test/Factories/PagingResponseFactoryTests.cs
- TramsDataApi.Test/Integration/AcademyConversionProjectsIntegrationTests.cs
- TramsDataApi.Test/UseCases/GetAcademyConversionProjectsByStatusesTests.cs
- TramsDataApi.Test/UseCases/GetAcademyConversionProjectsTests.cs
- TramsDataApi/Controllers/AcademyConversionProjectController.cs
- TramsDataApi/Controllers/V2/AcademyConversionProjectController.cs
- TramsDataApi/Gateways/AcademyConversionProjectGateway.cs
- TramsDataApi/Gateways/IAcademyConversionProjectGateway.cs
- TramsDataApi/Gateways/IIfdPipelineGateway.cs
- TramsDataApi/Gateways/IfdPipelineGateway.cs
- TramsDataApi/RequestModels/AcademyConversionProject/GetAcademyConversionProjectsByStatusesRequest.cs
- TramsDataApi/RequestModels/AcademyConversionProject/GetAllAcademyConversionProjectsRequest.cs
- TramsDataApi/ResponseModels/ApiResponseV2.cs
- TramsDataApi/ResponseModels/PagingResponse.cs
- TramsDataApi/ResponseModels/PagingResponseFactory.cs
- TramsDataApi/UseCases/GetAcademyConversionProjects.cs
- TramsDataApi/UseCases/GetAcademyConversionProjectsByStatuses.cs
> 74379 add paging to api v2 response

- TramsDataApi.ApplyToBecome/SyncAcademyConversionProject.cs
- TramsDataApi.ApplyToBecome/SyncAcademyConversionProjectFactory.cs
- TramsDataApi.Test/ApplyToBecome/SyncAcademyConversionProjectFactoryTests.cs
- TramsDataApi.Test/Factories/AcademyConversionProjectFactoryTests.cs
- TramsDataApi.Test/Factories/AcademyConversionProjectResponseFactoryTests.cs
- TramsDataApi/DatabaseModels/AcademyConversionProject.cs
- TramsDataApi/Factories/AcademyConversionProjectFactory.cs
- TramsDataApi/Factories/AcademyConversionProjectResponseFactory.cs
- TramsDataApi/Migrations/TramsDb/20210922143120_A2B-AddConversionGrantFields.Designer.cs
- TramsDataApi/Migrations/TramsDb/20210922143120_A2B-AddConversionGrantFields.cs
- TramsDataApi/RequestModels/AcademyConversionProject/UpdateAcademyConversionProjectRequest.cs
- TramsDataApi/ResponseModels/AcademyConversionProject/AcademyConversionProjectResponse.cs
- Add conversion grant amount to academy conversion project
- Sets the existing entries to the default amount
- Set and get academy conversion grant amounts
> Add conversion support grant to a2b projects

- TramsDataApi.Test/Controllers/ConcernsCaseControllerTests.cs
- TramsDataApi.Test/Factories/ConcernsCaseFactoryTests.cs
- TramsDataApi.Test/Factories/ConcernsCaseResponseFactoryTests.cs
- TramsDataApi.Test/Integration/ConcernsIntegrationTests.cs
- TramsDataApi.Test/UseCases/CreateConcernsCaseTests.cs
- TramsDataApi/Controllers/V2/ConcernsCaseController.cs
- TramsDataApi/DatabaseModels/ConcernsCase.cs
- TramsDataApi/DatabaseModels/ConcernsStatus.cs
- TramsDataApi/DatabaseModels/TramsDbContext.cs
- TramsDataApi/Factories/ConcernsCaseFactory.cs
- TramsDataApi/Factories/ConcernsCaseResponseFactory.cs
- TramsDataApi/Gateways/ConcernsCaseGateway.cs
- TramsDataApi/Gateways/IConcernsCaseGateway.cs
- TramsDataApi/Migrations/TramsDb/20211020181404_AddConcernsCaseMigration.Designer.cs
- TramsDataApi/Migrations/TramsDb/20211020181404_AddConcernsCaseMigration.cs
- TramsDataApi/RequestModels/ConcernCaseRequest.cs
- TramsDataApi/ResponseModels/ConcernsCaseResponse.cs
- TramsDataApi/Startup.cs
- TramsDataApi/UseCases/CreateConcernsCase.cs
- TramsDataApi/UseCases/ICreateConcernsCase.cs
This PR:
- Adds the concerns case and concerns status db models and migrations.
- Add the POST route to create concerns cases.
> Add concerns cases

- TramsDataApi.Test/Factories/ConcernsRecordFactoryTests.cs
- TramsDataApi.Test/Factories/ConcernsRecordResponseFactoryTests.cs
- TramsDataApi.Test/Integration/ConcernsIntegrationTests.cs
- TramsDataApi.Test/UseCases/CreateConcernsCaseTests.cs
- TramsDataApi.Test/UseCases/CreateConcernsRecordTests.cs
- TramsDataApi/Controllers/V2/ConcernsRecordController.cs
- TramsDataApi/DatabaseModels/ConcernsRecord.cs
- TramsDataApi/DatabaseModels/ConcernsType.cs
- TramsDataApi/DatabaseModels/TramsDbContext.cs
- TramsDataApi/Factories/ConcernsRecordFactory.cs
- TramsDataApi/Factories/ConcernsRecordResponseFactory.cs
- TramsDataApi/Gateways/ConcernsRecordGateway.cs
- TramsDataApi/Gateways/IConcernsRecordGateway.cs
- TramsDataApi/Migrations/TramsDb/20211109135135_AddConcernsRecordMigration.Designer.cs
- TramsDataApi/Migrations/TramsDb/20211109135135_AddConcernsRecordMigration.cs
- TramsDataApi/RequestModels/ConcernsRecordRequest.cs
- TramsDataApi/ResponseModels/ConcernsRecordResponse.cs
- TramsDataApi/Startup.cs
- TramsDataApi/UseCases/CreateConcernsRecord.cs
- TramsDataApi/UseCases/ICreateConcernsRecord.cs
This PR:
- Add the DB Model and Migration for `ConcernsRecord` and `ConcernsType`
- Add the `ConcernsRecord` gateway
- Add the create `ConcernsRecord`
- Add the `ConcernsRecord` controller and POST route to create a `ConcernsRecord`
> Add create concerns record route

- TramsDataApi.Test/Factories/ConcernsRatingResponseFactoryTests.cs
- TramsDataApi.Test/Factories/ConcernsRecordFactoryTests.cs
- TramsDataApi.Test/Factories/ConcernsRecordResponseFactoryTests.cs
- TramsDataApi.Test/Integration/ConcernsIntegrationTests.cs
- TramsDataApi.Test/UseCases/CreateConcernsRecordTests.cs
- TramsDataApi.Test/UseCases/IndexConcernsRatingsTests.cs
- TramsDataApi/Controllers/V2/ConcernsRatingController.cs
- TramsDataApi/DatabaseModels/ConcernsRating.cs
- TramsDataApi/DatabaseModels/ConcernsRecord.cs
- TramsDataApi/DatabaseModels/TramsDbContext.cs
- TramsDataApi/Factories/ConcernsRatingResponseFactory.cs
- TramsDataApi/Factories/ConcernsRecordFactory.cs
- TramsDataApi/Factories/ConcernsRecordResponseFactory.cs
- TramsDataApi/Gateways/ConcernsRatingsGateway.cs
- TramsDataApi/Gateways/IConcernsRatingGateway.cs
- TramsDataApi/Migrations/TramsDb/20211115121238_AddConcernsRatingsMigration.Designer.cs
- TramsDataApi/Migrations/TramsDb/20211115121238_AddConcernsRatingsMigration.cs
- TramsDataApi/RequestModels/ConcernsRecordRequest.cs
- TramsDataApi/ResponseModels/ConcernsRatingResponse.cs
- TramsDataApi/ResponseModels/ConcernsRecordResponse.cs
- TramsDataApi/Startup.cs
- TramsDataApi/UseCases/CreateConcernsRecord.cs
- TramsDataApi/UseCases/IIndexConcernsRatings.cs
- TramsDataApi/UseCases/IndexConcernsRatings.cs
In this PR:
- Add the Concerns Ratings db model and migration
- Add Concerns Ratings Response object and factory
- Update Concerns Records to add add Ratings
- Add Index Concerns Ratings endpoint
> Add concerns ratings

- TramsDataApi.Test/Factories/ConcernsRecordResponseFactoryTests.cs
- TramsDataApi.Test/Integration/ConcernsIntegrationTests.cs
- TramsDataApi.Test/UseCases/UpdateConcernsRecordTests.cs
- TramsDataApi/Controllers/V2/ConcernsRecordController.cs
- TramsDataApi/DatabaseModels/ConcernsRecord.cs
- TramsDataApi/Factories/ConcernsRecordFactory.cs
- TramsDataApi/Gateways/ConcernsRecordGateway.cs
- TramsDataApi/Gateways/IConcernsRecordGateway.cs
- TramsDataApi/Migrations/TramsDb/20211117161151_UpdateConcernsRecordsUrnMigration.Designer.cs
- TramsDataApi/Migrations/TramsDb/20211117161151_UpdateConcernsRecordsUrnMigration.cs
- TramsDataApi/ResponseModels/ConcernsRecordResponse.cs
- TramsDataApi/Startup.cs
- TramsDataApi/UseCases/IUpdateConcernsRecord.cs
- TramsDataApi/UseCases/UpdateConcernsRecord.cs
In this PR:
- Add update method to concerns record gateway
- Add update concerns usecase
- Add update method to concerns record factory
- Add Patch route to update concerns records
> Add patch route for updating records

- TramsDataApi.Test/Factories/AcademyConversionProjectFactoryTests.cs
- TramsDataApi.Test/Factories/AcademyConversionProjectResponseFactoryTests.cs
- TramsDataApi/DatabaseModels/AcademyConversionProject.cs
- TramsDataApi/Factories/AcademyConversionProjectFactory.cs
- TramsDataApi/Factories/AcademyConversionProjectResponseFactory.cs
- TramsDataApi/Migrations/TramsDb/20211118112906_AddMPNameToAcademyConversionProject.Designer.cs
- TramsDataApi/Migrations/TramsDb/20211118112906_AddMPNameToAcademyConversionProject.cs
- TramsDataApi/RequestModels/AcademyConversionProject/UpdateAcademyConversionProjectRequest.cs
- TramsDataApi/ResponseModels/AcademyConversionProject/AcademyConversionProjectResponse.cs
Added fields to the Academy conversions project
> Academy conversion - added MP name and party, Get and Update

- TramsDataApi.Test/Controllers/ConcernsCaseControllerTests.cs
- TramsDataApi.Test/Integration/ConcernsIntegrationTests.cs
- TramsDataApi.Test/UseCases/GetConcernsCasesByOwnerIdTests.cs
- TramsDataApi/Controllers/V2/ConcernsCaseController.cs
- TramsDataApi/Gateways/ConcernsCaseGateway.cs
- TramsDataApi/Gateways/IConcernsCaseGateway.cs
- TramsDataApi/Startup.cs
- TramsDataApi/UseCases/GetConcernsCasesByOwnerId.cs
- TramsDataApi/UseCases/IGetConcernsCasesByOwnerId.cs
In this PR: 
- Add Get Concerns Case by OwnerId gateway method
- Add Get Concerns Case by OwnerId usecase
- Add `concerns-cases/owner/{ownerId}` route
> Add get concerns case by owner

- TramsDataApi.Test/Controllers/A2BApplicationControllerTests.cs
- TramsDataApi.Test/Controllers/A2BApplicationKeyPersonsControllerTests.cs
- TramsDataApi.Test/Factories/A2BApplicationKeyPersonsFactoryTests.cs
- TramsDataApi.Test/Factories/A2BApplicationKeyPersonsResponseFactoryTests.cs
- TramsDataApi.Test/Integration/ApplyToBecomeIntegrationTests.cs
- TramsDataApi.Test/UseCases/CreateA2BApplicationKeyPersonsTests.cs
- TramsDataApi.Test/UseCases/CreateA2BApplicationTests.cs
- TramsDataApi.Test/UseCases/GetA2BApplicationKeyPersonsTests.cs
- TramsDataApi/Controllers/V2/A2BApplicationKeyPersonsController.cs
- TramsDataApi/DatabaseModels/A2BApplicationKeyPersons.cs
- TramsDataApi/Factories/A2BApplicationKeyPersonsFactory.cs
- TramsDataApi/Factories/A2BApplicationKeyPersonsResponseFactory.cs
- TramsDataApi/Gateways/A2BApplicationGateway.cs
- TramsDataApi/Gateways/A2BApplicationKeyPersonsGateway.cs
- TramsDataApi/Gateways/IA2BApplicationKeyPersonsGateway.cs
- TramsDataApi/Migrations/TramsDb/20211123162758_AddDbGeneratedIdColumnToA2BApplicationKeyPersons.Designer.cs
- TramsDataApi/Migrations/TramsDb/20211123162758_AddDbGeneratedIdColumnToA2BApplicationKeyPersons.cs
- TramsDataApi/RequestModels/ApplyToBecome/A2BApplicationKeyPersonsByIdRequest.cs
- TramsDataApi/RequestModels/ApplyToBecome/A2BApplicationKeyPersonsCreateRequest.cs
- TramsDataApi/ResponseModels/ApplyToBecome/A2BApplicationKeyPersonsResponse.cs
- TramsDataApi/ResponseModels/ApplyToBecome/A2BApplicationResponse.cs
- TramsDataApi/Startup.cs
- TramsDataApi/Swagger/SwaggerOptions.cs
- TramsDataApi/UseCases/CreateA2BApplicationKeyPersons.cs
- TramsDataApi/UseCases/GetA2BApplicationKeyPersons.cs
- TramsDataApi/UseCases/ICreateA2BApplicationKeyPersons.cs
- TramsDataApi/UseCases/IGetA2BApplicationKeyPersons.cs
This PR includes:
Create Get endpoint for `/apply-to-become/keyPersons/{keyPersonId}`
Create Post endpoint for `/apply-to-become/keyPersons`
Add Gateway, UseCases, Models and Factories
Add Associated Unit and Integration Tests
Add Services to Startup
General code cleanup of usings / unused methods
> A2b create get post endpoints for application key persons

- TramsDataApi.Test/Controllers/A2BApplicationStatusControllerTests.cs
- TramsDataApi.Test/Factories/A2BApplicationStatusFactoryTests.cs
- TramsDataApi.Test/Factories/A2BApplicationStatusResponseFactoryTests.cs
- TramsDataApi.Test/Integration/ApplyToBecomeIntegrationTests.cs
- TramsDataApi.Test/UseCases/CreateA2BApplicationStatusTests.cs
- TramsDataApi.Test/UseCases/GetA2BApplicationStatusTests.cs
- TramsDataApi/Controllers/V2/A2BApplicationStatusController.cs
- TramsDataApi/DatabaseModels/A2BApplicationStatus.cs
- TramsDataApi/Factories/A2BApplicationStatusFactory.cs
- TramsDataApi/Factories/A2BApplicationStatusResponseFactory.cs
- TramsDataApi/Gateways/A2BApplicationStatusGateway.cs
- TramsDataApi/Gateways/IA2BApplicationStatusGateway.cs
- TramsDataApi/Migrations/TramsDb/20211130165933_ChangeA2BApplicationStatusIdColumnToInt.Designer.cs
- TramsDataApi/Migrations/TramsDb/20211130165933_ChangeA2BApplicationStatusIdColumnToInt.cs
- TramsDataApi/RequestModels/ApplyToBecome/A2BApplicationStatusCreateRequest.cs
- TramsDataApi/ResponseModels/ApplyToBecome/A2BApplicationStatusResponse.cs
- TramsDataApi/Startup.cs
- TramsDataApi/UseCases/CreateA2BApplicationStatus.cs
- TramsDataApi/UseCases/GetA2BApplicationStatus.cs
- TramsDataApi/UseCases/ICreateA2BApplicationStatus.cs
- TramsDataApi/UseCases/IGetA2BApplicationStatus.cs
Add DBMigration to change string column to db generated int
Add Get / Post Endpoints for A2BApplicationStatus
Create gateway and use cases
Create Response / Request Models
Create ResponseModel Factories
Create Associated Unit and Integration Tests
> Add GET / Post Endpoints for A2BApplicationStatus

- TramsDataApi.sln
Adding the readme.md to the solution items so that it's easy to open in Visual Studio
> Added readme to solution items

- CypressTests/cypress/integration/conversions/api_apply-to-become/schemaJson.js
- CypressTests/cypress/schemas/schema.js
- CypressTests/cypress/support/commands.js
- CypressTests/cypress/support/validate-schema-command.js
- CypressTests/package-lock.json
- CypressTests/package.json
Tests:
- json schema: apply-to-become API V2
- additional commands
Library dependencies:
- AJV
- AJV Formats
> 89785: Test against json schema

- CypressTests/cypress/integration/conversions/89770_api_apply-to-become/89785_schemaJson.js
- changes to reflect schema update
> Fix: Un-skip test

- TramsDataApi.Test/Controllers/SRMAControllerTests.cs
- TramsDataApi.Test/Factories/SRMAFactoryTests.cs
- TramsDataApi.Test/UseCases/CreateSRMATests.cs
- TramsDataApi/Controllers/V2/SRMAController.cs
- TramsDataApi/DatabaseModels/SRMACase.cs
- TramsDataApi/Enums/SRMAReasonOffered.cs
- TramsDataApi/Enums/SRMAStatus.cs
- TramsDataApi/Factories/CaseActionFactories/SRMAFactory.cs
- TramsDataApi/Gateways/ISRMAGateway.cs
- TramsDataApi/Gateways/SRMAGateway.cs
- TramsDataApi/RequestModels/CaseActions/SRMA/CreateSRMARequest.cs
- TramsDataApi/ResponseModels/CaseActions/SRMA/CreateSRMAResponse.cs
- TramsDataApi/Startup.cs
- TramsDataApi/UseCases/CaseActions/CreateSRMA.cs
What is the change?
All layers required for SRMA controller 
First endpoint (create SRMA)
Unit tests 
Why do we need the change?
New SRMA controller
What is the impact?
New controller and supporting services. No impact to existing features.
Azure DevOps Ticket
90777
> Feature/90777 API layers and first endpoint for SRMA project

- TramsDataApi.Test/Controllers/SRMAControllerTests.cs
- TramsDataApi/Controllers/V2/SRMAController.cs
Temporarily remove endpoint to fix Swagger error on dev.
> Temporarily remove endpoint to fix Swagger error on dev.

- TramsDataApi.Test/Factories/AcademyTransferProjectFactoryTests.cs
- TramsDataApi/Controllers/AcademyTransferProjectController.cs
- TramsDataApi/RequestModels/AcademyTransferProjectRequest.cs
- TramsDataApi/ResponseModels/AcademyTransferProjectResponse.cs
Missed the request and response models previously
> Remove columns from Request and Response models AB#87757

- TramsDataApi.Test/Factories/AcademyConversionProjectResponseFactoryTests.cs
- TramsDataApi/Factories/AcademyConversionProjectResponseFactory.cs
map EqualitiesImpactAssessmentConsidered response variable in the AcademiesConversionProject Get response
relates to bug fix tasks 95520 and 95527 in pre-AB
No migration changes
> AcademyConversionProject - add a missing mapping

- TramsDataApi.Test/Factories/AcademyConversionProjectResponseFactoryTests.cs
- TramsDataApi/Factories/AcademyConversionProjectResponseFactory.cs
Reverts DFE-Digital/trams-data-api#192
> Revert "AcademyConversionProject - add a missing mapping"

- CypressTests/cypress/schemas/schema.js
- TramsDataApi.Test/Factories/A2BApplicationFactoryTests.cs
- TramsDataApi.Test/Integration/ApplyToBecomeIntegrationTests.cs
- TramsDataApi/DatabaseModels/A2BApplication.cs
- TramsDataApi/Factories/A2BApplicationFactories/A2BApplicationFactory.cs
- TramsDataApi/Migrations/TramsDb/20220525133627_TrustNameAddedToA2BApplication.Designer.cs
- TramsDataApi/Migrations/TramsDb/20220525133627_TrustNameAddedToA2BApplication.cs
- TramsDataApi/RequestModels/ApplyToBecome/A2BApplicationCreateRequest.cs
- TramsDataApi/ResponseModels/ApplyToBecome/A2BApplicationResponse.cs
Added the trust name to the A2BApplication table and API response.
> Added TrustName to A2BApplication

- CypressTests/cypress/integration/academytransfers/academyTransferE2E.js
- CypressTests/cypress/integration/conversions/89770_api_apply-to-become/89785_schemaJson.js
- CypressTests/cypress/schemas/schema.js
Includes:
- Update to schema tests
- Commented out tests which are redudant and requires updating
> Task 97599: Fix trams-api-automation tests

- .github/workflows/test.yml
- TramsDataApi.Test/Controllers/AcademyConversionProjectsControllerTests.cs
- TramsDataApi.Test/Controllers/AcademyConversionProjectsControllerV2Tests.cs
- TramsDataApi.Test/Factories/AcademyConversionProjectResponseFactoryTests.cs
- TramsDataApi.Test/Integration/AcademyConversionProjectsIntegrationTests.cs
- TramsDataApi.Test/UseCases/GetAcademyConversionProjectsByStatusesTests.cs
- TramsDataApi.Test/UseCases/GetAcademyConversionProjectsTests.cs
- TramsDataApi/Controllers/AcademyConversionProjectController.cs
- TramsDataApi/Controllers/V2/AcademyConversionProjectController.cs
- TramsDataApi/Factories/AcademyConversionProjectResponseFactory.cs
- TramsDataApi/Gateways/AcademyConversionProjectGateway.cs
- TramsDataApi/Gateways/IAcademyConversionProjectGateway.cs
- TramsDataApi/Startup.cs
- TramsDataApi/UseCases/GetAcademyConversionProject.cs
- TramsDataApi/UseCases/GetAcademyConversionProjects.cs
- TramsDataApi/UseCases/GetAcademyConversionProjectsByStatuses.cs
- TramsDataApi/UseCases/IGetAcademyConversionProject.cs
- TramsDataApi/UseCases/IGetAcademyConversionProjects.cs
- TramsDataApi/UseCases/IGetAcademyConversionProjectsByStatuses.cs
- TramsDataApi/UseCases/UpdateAcademyConversionProject.cs
Remove now unnecessary references to other data sources which are no longer required.
Add order to EF queries to retrieve most recent projects first
Update tests
General Refactoring.
> Refactor and rewrite of the academy conversion project 

- TramsDataApi/Factories/CaseActionFactories/FinancialPlanFactory.cs
minor change - changed name from previous copy+paste
> changed name

- CypressTests/cypress/integration/conversions/order-project-by-date.js
- CypressTests/cypress/support/commands.js
- Fetches & sorts project dates by random
- Asserts that first project has most recent timestamp
> Task 100103:  Ordering of projects

- TramsDataApi.Test/Factories/AcademyTransferProjectFactoryTests.cs
- TramsDataApi.Test/Factories/AcademyTransferProjectResponseFactoryTests.cs
- TramsDataApi.Test/Integration/AcademyTransferProjectIntegrationTests.cs
- TramsDataApi.Test/UseCases/CreateAcademyTransferProjectTests.cs
- TramsDataApi/DatabaseModels/AcademyTransferProjects.cs
- TramsDataApi/DatabaseModels/TramsDbContext.cs
- TramsDataApi/Factories/AcademyTransferProjectFactory.cs
- TramsDataApi/Factories/AcademyTransferProjectResponseFactory.cs
- TramsDataApi/Migrations/TramsDb/20220721081236_HtbDateInsertedAndHasHtbDateInserted.Designer.cs
- TramsDataApi/Migrations/TramsDb/20220721081236_HtbDateInsertedAndHasHtbDateInserted.cs
- TramsDataApi/RequestModels/AcademyTransferProjectDatesRequest.cs
- TramsDataApi/ResponseModels/AcademyTransferProjectDatesResponse.cs
Reverts DFE-Digital/trams-data-api#216
> Revert "Revert "Added HtbDateInserted and HasHtbDateInserted properties""

- TramsDataApi.Test/Factories/AcademyTransferProjectFactoryTests.cs
- TramsDataApi.Test/Factories/AcademyTransferProjectResponseFactoryTests.cs
- TramsDataApi.Test/Integration/AcademyTransferProjectIntegrationTests.cs
- TramsDataApi.Test/UseCases/CreateAcademyTransferProjectTests.cs
- TramsDataApi/DatabaseModels/AcademyTransferProjects.cs
- TramsDataApi/DatabaseModels/TramsDbContext.cs
- TramsDataApi/Factories/AcademyTransferProjectFactory.cs
- TramsDataApi/Factories/AcademyTransferProjectResponseFactory.cs
- TramsDataApi/Migrations/TramsDb/20220801132947_RemoveHTBDateInsertedAndHTBHasDateInserted.Designer.cs
- TramsDataApi/Migrations/TramsDb/20220801132947_RemoveHTBDateInsertedAndHTBHasDateInserted.cs
- TramsDataApi/RequestModels/AcademyTransferProjectDatesRequest.cs
Removing as requested by Moses
> Remove HTBInsertedDate and HasHTBDateInserted

- CypressTests/cypress/integration/conversions/89770_api_apply-to-become/89785_schemaJson.js
- CypressTests/cypress/integration/conversions/GET conversion-projects/get-conversion-projects-with-id.js
- CypressTests/cypress/integration/conversions/GET conversion-projects/get-conversion-projects.js
- CypressTests/cypress/integration/conversions/PATCH conversion-projects/patch-conversion-projects-with-id.js
- Updated ID on schema tests
- Update to URLS, removing unnecessary  slashes '/'
- Updated PATCH tests
> Task 102484: Fix failing Cypress Test on TRAMS api

- TramsDataApi.Test/Factories/AcademyConversionProjectFactoryTests.cs
- TramsDataApi/Factories/AcademyConversionProjectFactory.cs
Update the AcademyConversionProject patch endpoint to allow the project status to be updated.
> 102877 - update project status on AcademyConversionProject patch 

- TramsDataApi.Test/Integration/AcademyTransferProjectIntegrationTests.cs
AB#101970 - Attempt to fix issue with unrelated test, this test appears to be flaky
> AB#101970 - Attempt to fix issue with unrelated test

- CypressTests/cypress/integration/conversions/order-project-by-date.js
- changes made to date ordering which returns it by ascending order
> Task 103984: Fix cypress tests for date order

- TramsDataApi/DatabaseModels/NoticeToImprove.cs
- TramsDataApi/Factories/CaseActionFactories/NoticeToImproveFactory.cs
- TramsDataApi/Migrations/TramsDb/20220907153708_AddNoticeToImprove.Designer.cs
- TramsDataApi/Migrations/TramsDb/20220907153708_AddNoticeToImprove.cs
- TramsDataApi/Migrations/TramsDb/TramsDbContextModelSnapshot.cs
- TramsDataApi/RequestModels/CaseActions/NTI/NoticeToImprove/PatchNoticeToImproveRequest.cs
- TramsDataApi/ResponseModels/CaseActions/NTI/NoticeToImprove/NoticeToImproveResponse.cs
> Add 3 fields to NTI model

- TramsDataApi.Test/Factories/NoticeToImproveFactoryTests.cs
> fix failing unit tests

- TramsDataApi.Test/Factories/AcademyConversionProjectFactoryTests.cs
- TramsDataApi/DatabaseModels/AcademyConversionProject.cs
- TramsDataApi/Factories/AcademyConversionProjectFactory.cs
- TramsDataApi/Migrations/TramsDb/20220920151312_Add_LegalRequirements.Designer.cs
- TramsDataApi/Migrations/TramsDb/20220920151312_Add_LegalRequirements.cs
- TramsDataApi/RequestModels/AcademyConversionProject/UpdateAcademyConversionProjectRequest.cs
- TramsDataApi/ResponseModels/AcademyConversionProject/AcademyConversionProjectResponse.cs
- TramsDataApi/UseCases/UpdateAcademyConversionProject.cs
Nice work. 
This has been marked as a draft, are there more changes to come?
> Added legal requirements fields, migration, and updated tests.

- TramsDataApi/DatabaseModels/TramsDbContext.cs
- TramsDataApi/Migrations/TramsDb/20220922134923_UpdateNTIWarningLetterStatuses.Designer.cs
- TramsDataApi/Migrations/TramsDb/20220922134923_UpdateNTIWarningLetterStatuses.cs
Updating incorrect values for warning letter status
> update warning letter status, past tense values

- TramsDataApi.Test/Controllers/AcademyConversionProjectsControllerV2Tests.cs
- TramsDataApi.Test/Integration/AcademyConversionProjectsIntegrationTests.cs
- TramsDataApi.Test/UseCases/SearchAcademyConversionProjectsTests.cs
- TramsDataApi/Controllers/V2/AcademyConversionProjectController.cs
- TramsDataApi/DatabaseModels/AcademyConversionProject.cs
- TramsDataApi/Factories/AcademyConversionProjectResponseFactory.cs
- TramsDataApi/Gateways/AcademyConversionProjectGateway.cs
- TramsDataApi/Gateways/IAcademyConversionProjectGateway.cs
- TramsDataApi/ResponseModels/PagingResponseFactory.cs
- TramsDataApi/UseCases/GetAcademyConversionProject.cs
- TramsDataApi/UseCases/GetAcademyConversionProjects.cs
- TramsDataApi/UseCases/ISearchAcademyConversionProjects.cs
- TramsDataApi/UseCases/SearchAcademyConversionProjects.cs
Ensuring the total number of projects for search is returned rather than number returned in result set.
Also a bit of tidying up.
> AB#101007 project filter - return total project count

- .github/workflows/test.yml
Include SonarCloud scanning on push to main branch
> Add merge to main for scanning

- TramsDataApi.Test/Factories/AcademyTransferProjectFactoryTests.cs
- TramsDataApi.Test/Factories/AcademyTransferProjectResponseFactoryTests.cs
- TramsDataApi/DatabaseModels/AcademyTransferProjects.cs
- TramsDataApi/DatabaseModels/TramsDbContext.cs
- TramsDataApi/Factories/AcademyTransferProjectFactory.cs
- TramsDataApi/Factories/AcademyTransferProjectResponseFactory.cs
- TramsDataApi/Migrations/TramsDb/20221117091538_Add_assigned_user_to_TransferProject.Designer.cs
- TramsDataApi/Migrations/TramsDb/20221117091538_Add_assigned_user_to_TransferProject.cs
- TramsDataApi/RequestModels/AcademyTransferProject/AcademyTransferProjectRequest.cs
- TramsDataApi/RequestModels/AssignedUserRequest.cs
- TramsDataApi/ResponseModels/AcademyTransferProject/AcademyTransferProjectResponse.cs
- TramsDataApi/ResponseModels/AssignedUserResponse.cs
> AB#107726 assign project - add assigned user to transfer project

- .github/workflows/continuous-integration-terraform.yml
- .github/workflows/continuous-integration-tfsec.yml
- Add `tfsec` scanner workflow
- Add `terraform validate` workflow
> Added new Terraform CI workflows

- .github/workflows/build-and-push-image-development.yml
- Adds a step to the deployment workflow that restarts the container on Azure Container Apps.
> Automate Dev container restart

- .github/workflows/build-and-push-image-test.yml
- Add a workflow that automates the deployment of the tag `prerelease` to the Test environment
> Add deployment workflow for test environment

- terraform/README.md
- terraform/key-vault-tfvars-secrets.tf
- Adds an expiration date to Key Vault secrets which resolves an Azure Security Posture item
> Updated Key Vault module to 0.1.3

- terraform/README.md
- terraform/container-apps-hosting.tf
- This adds a number of diagnostic settings and improves network access rules for storage accounts
> Updated Container App Terraform module to 0.17.4

- .github/workflows/continuous-integration-dotnet.yml
Updates the project key for SonarCloud to match https://sonarcloud.io/project/overview?id=DFE-Digital_academies-api
> Update SonarCloud project key

- Dockerfile
fixes the aspnet docker base image
> changed asp.net image to 6.0.9-bullseye-slim

- CypressTests/docker-compose.yml
Fix path on volume mount to report directory
> Hotfix Update Cypress docker-compose.yml

- CypressTests/.eslintrc.json
- CypressTests/package-lock.json
- CypressTests/package.json
Adds the capability to use eslint for the Cypress test directory, in line with the RSD testing strategy
> Add Cypress linting script

- TramsDataApi/TramsDataApi.csproj
Updated correlation id middleware so that empty guid detection in correlation id header will work
> updated correlation id middleware

- TramsDataApi/DatabaseModels/TramsDbContext.cs
- TramsDataApi/Migrations/TramsDb/20230712114342_academy-transfer-project-urn_sdd_schema.Designer.cs
- TramsDataApi/Migrations/TramsDb/20230712114342_academy-transfer-project-urn_sdd_schema.cs
- TramsDataApi/Migrations/TramsDb/20230712121010_remove-sequence-academy-transfer-project-urns.Designer.cs
- TramsDataApi/Migrations/TramsDb/20230712121010_remove-sequence-academy-transfer-project-urns.cs
fix sequence issues in transfers, should no longer get a duplicate URN
> Academy transfer project duplicate urn fix

- TramsDataApi.Test/FakeApi/FakeMfspApi.cs
- TramsDataApi.Test/integration_settings.json
- TramsDataApi/Configuration/MfspOptions.cs
- TramsDataApi/Startup.cs
- TramsDataApi/TramsDataApi.csproj
- TramsDataApi/UseCases/GetAllFssProjects.cs
- TramsDataApi/appsettings.json
updated the api endpoint and contract
added an app key
> 155067: integrate get construct projects

- TramsDataApi.Test/UseCases/GetEstablishmentsTests.cs
- TramsDataApi/Controllers/EstablishmentsController.cs
- TramsDataApi/Gateways/EstablishmentGateway.cs
- TramsDataApi/Gateways/IEstablishmentGateway.cs
- TramsDataApi/RequestModels/GetEstablishmentsByUkprnsRequest.cs
- TramsDataApi/UseCases/GetEstablishments.cs
- TramsDataApi/UseCases/IGetEstablishments.cs
https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_workitems/edit/165019
> get bulk establishments by UKPRN

- README.md
Updating and clarifying references to TRAMS in project documentation.
> Clarifying references to TRAMS in README document

- PersonsApi/Controllers/ConstituenciesController.cs
- PersonsApi/UseCases/ApiKeyService.cs
- PersonsApi/appsettings.Development.json
- PersonsApi/appsettings.json
Updated API key app settings and service
> Updated API key app settings and service

- TramsDataApi/Startup.cs
Added missing AutoMapper dependency
> Added missing AutoMapper dependency

- Dockerfile
- Dockerfile.PersonsApi
Updated dotnet tools version to 8.0.8 in the dockerfiles
> Updated dotnet tools version to 8.0.8 in the dockerfiles

- Dfe.Academies.Api.Infrastructure/MstrContext.cs
- Dfe.Academies.Application/Common/Behaviours/UnhandledExceptionBehaviour.cs
- Dfe.Academies.Domain/Constituencies/Constituency.cs
- Dfe.Academies.Domain/Constituencies/MemberContactDetails.cs
- Dfe.Academies.Domain/Establishment/Establishment.cs
- Dfe.Academies.Domain/Establishment/GovernanceRoleType.cs
- PersonsApi/Middleware/ExceptionHandlerMiddleware.cs
- Tests/Dfe.Academies.PersonsApi.Tests.Integration/Controllers/EstablishmentsControllerTests.cs
- Tests/Dfe.Academies.PersonsApi.Tests.Integration/OpenApiTests/OpenApiDocumentTests.cs
- Tests/Dfe.Academies.Testing.Common/Customizations/CustomWebApplicationDbContextFactoryCustomization.cs
- Tests/Dfe.Academies.Testing.Common/Customizations/CustomWebApplicationFactoryCustomization.cs
- Tests/Dfe.Academies.Testing.Common/Customizations/DbContextCustomization.cs
- Tests/Dfe.Academies.Testing.Common/Helpers/DbContextHelper.cs
- Tests/Dfe.Academies.Testing.Common/Mocks/CustomWebApplicationDbContextFactory.cs
- Tests/Dfe.Academies.Testing.Common/Mocks/CustomWebApplicationFactory.cs
- Tests/Dfe.Academies.Testing.Common/Mocks/MockJwtBearerHandler.cs
> Fixed code smells

- .github/workflows/continuous-integration-dotnet.yml
Some github CI actions are not triggering on certain PRs
> Be more specific with paths

- LICENCE
https://technical-guidance.education.gov.uk/standards/licencing-software-or-code/#applying-the-mit-license-to-our-work
> Corrected MIT licence

- Dockerfile
* autoaccept the installation of any available patches
> Restrict scope of update task to security packages only

- .dockerignore
- .github/workflows/build-and-push-image.yml
- .github/workflows/docker-build.yml
- .github/workflows/docker-test.yml
- Dockerfile
- script/web-docker-entrypoint.sh
- terraform/README.md
- terraform/container-apps-hosting.tf
- terraform/locals.tf
- terraform/variables.tf
- Update Academies API Docker image and workflow to make use of Entity Framework Migration Bundles
> EF Migration Bundle for Academies API

- TramsDataApi/TramsDataApi.csproj
Removed nswag builder for now, this can be added later.
> Removed nswag builder

- Dockerfile
* This should get picked up automatically by MSBuild as it is defined in ENV
> Remove project parameters flag for CI var

- TramsDataApi/SerilogCustomEnrichers/ApiUserEnricher.cs
The Log message was incorrectly spelt
> Fix spelling

- Dockerfile
- Removing the `"` characters in the `FROM` statements allows Renovate to pick up the layer names correctly.
- Consolidating `RUN` commands improves build caching and speeds up build time
- Splitting long lines resolves warnings from SonarQube
> Reduced build layers and aligned to SonarQube quality rules

- Dfe.Academies.Api.Infrastructure/MstrContext.cs
- Dfe.Academies.Api.Infrastructure/Repositories/EstablishmentRepository.cs
- Dfe.Academies.Application/Dfe.Academies.Application.csproj
- Dfe.Academies.Application/Establishment/EstablishmentDtoBuilder.cs
- Dfe.Academies.Application/Establishment/EstablishmentQueries.cs
- Dfe.Academies.Domain/Establishment/EducationEstablishmentLink.cs
- Dfe.Academies.Domain/Establishment/PreviousEstablishment.cs
- Dfe.Academies.Domain/Interfaces/Repositories/IEstablishmentRepository.cs
- Dfe.AcademiesApi.Client/Generated/Contracts.g.cs
- Dfe.AcademiesApi.Client/Generated/swagger.json
- Tests/Dfe.Academies.Application.Tests/Queries/Establishment/EstablishmentQueriesTests.cs
Added previous establishment with URN info to response 
With Previous URN (Predecessor Only)
Without Previous URN
> Added previous establishment with URN info to response

- Dfe.Academies.Api.Infrastructure/Repositories/TrustRepository.cs
- Dfe.Academies.Application/Trust/ITrustQueries.cs
- Dfe.Academies.Application/Trust/TrustQueries.cs
- Dfe.Academies.Domain/Interfaces/Repositories/ITrustRepository.cs
- Dfe.Academies.TramsDataApi.Tests.Integration/Controllers/V4/TrustsControllersTests.cs
- Dfe.AcademiesApi.Client/Generated/Client.g.cs
- Dfe.AcademiesApi.Client/Generated/Contracts.g.cs
- Dfe.AcademiesApi.Client/Generated/swagger.json
- Tests/Dfe.Academies.Application.Tests/Queries/Trust/TrustQueriesTests.cs
- Tests/Dfe.Academies.Tests.Common/Customizations/CustomWebApplicationDbContextFactoryCustomization.cs
- TramsDataApi/Controllers/V4/TrustsController.cs
Get Trusts by establishments URNs
Endpoint: https://{baseURL}/v4/trusts/establishments/urns
HTTP Verb: POST
[Azure DevOps ticket](https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_workitems/edit/223376)
Sample output
```
{
"129342": {
"name": "Test LEARNING TRUST",
"ukprn": "20023513",
"type": {
"name": "Multi-academy trust",
"code": "06"
},
"companiesHouseNumber": "08525800",
"referenceNumber": "TR02890",
"address": {
"street": null,
"town": "Town",
"county": null,
"postcode": "NG13 6DJ",
"locality": null,
"additional": "Brackley Road"
}
}
}
```
> Get Trusts by establishments URNs
