DFE-Digital/academies-api

- TramsDataApi.Test/Controllers/EstablishmentsControllerTests.cs
- TramsDataApi.Test/Controllers/TrustsControllerTests.cs
- TramsDataApi.Test/Factories/TrustListItemResponseFactoryTests.cs
- TramsDataApi.Test/Integration/TrustsIntegrationTests.cs
- TramsDataApi.Test/UseCases/SearchTrustsTests.cs
- TramsDataApi/Controllers/EstablishmentsController.cs
- TramsDataApi/Controllers/TrustsController.cs
- TramsDataApi/DatabaseModels/TramsDbContext.cs
- TramsDataApi/Factories/EstablishmentListItemResponseFactory.cs
- TramsDataApi/Factories/TrustListItemResponseFactory.cs
- TramsDataApi/Gateways/ITrustGateway.cs
- TramsDataApi/Gateways/TrustGateway.cs
- TramsDataApi/ResponseModels/EstablishmentListItemResponse.cs
- TramsDataApi/ResponseModels/TrustListItemResponse.cs
- TramsDataApi/Startup.cs
- TramsDataApi/UseCases/ISearchTrusts.cs
- TramsDataApi/UseCases/SearchTrusts.cs
Adds the `/trusts` route to the API, that allows the consumer to search for a list of truncated Trust response objects by `Group Name`, `Urn` or `Companies House Number`
> Index trusts

- TramsDataApi.Test/Controllers/EstablishmentsControllerTests.cs
- TramsDataApi.Test/Factories/EstablishmentResponseFactoryTests.cs
- TramsDataApi.Test/Integration/EstablishmentsIntegrationTests.cs
- TramsDataApi.Test/UseCases/GetEstablishmentByUkprnTests.cs
- TramsDataApi/Controllers/EstablishmentsController.cs
- TramsDataApi/Gateways/EstablishmentGateway.cs
- TramsDataApi/Gateways/IEstablishmentGateway.cs
- TramsDataApi/Gateways/TrustGateway.cs
- TramsDataApi/RequestModels/GetEstablishmentByUrnRequest.cs
- TramsDataApi/Startup.cs
- TramsDataApi/UseCases/GetEstablishment.cs
- TramsDataApi/UseCases/GetEstablishmentByUkprn.cs
The table for academy conversion projects only appears to have URNs and UKPRNs always seem to be null. In production some do have UKPRNS but it seems A2B can't rely on this so I've added a second route to get the establishment data using the URN
> Added route to get establishment by URN

- TramsDataApi.Test/Factories/AcademyConversionProjectResponseFactoryTests.cs
- TramsDataApi/Factories/AcademyConversionProjectResponseFactory.cs
- TramsDataApi/ResponseModels/AcademyConversionProject/AcademyConversionProjectResponse.cs
- TramsDataApi/ResponseModels/AcademyConversionProject/DocumentDetailsResponse.cs
- TramsDataApi/ResponseModels/AcademyConversionProject/RationaleResponse.cs
- TramsDataApi/appsettings.Development.json
Add a `Rationale` property to the `AcademyConversionProjectResponse`, where this property is of type `RationaleResponse` - an object containing two properties for the `ProjectRationale` (rationale for the project) and `TrustRationale` (rationale for the trust or sponsor) respectively.
This change is necessary because the rationale details are needed for the a2b internal service.
> Add rationale fields to academy conversion project response

- TramsDataApi.Test/Integration/TrustsIntegrationTests.cs
- TramsDataApi/Gateways/TrustGateway.cs
Previously the search trusts would do a strict `AND` search with the given fields; only trusts with matching `ukprn` AND `companiesHouseNumber` AND `groupName` would be returned. This replaces that with an OR search, so as long as any one of those fields are matched, the Trust will be returned.
> Updated searching to return values based on all matches

- TramsDataApi.Test/Factories/AcademyConversionProjectResponseFactoryTests.cs
- TramsDataApi/Factories/AcademyConversionProjectResponseFactory.cs
- TramsDataApi/ResponseModels/AcademyConversionProject/RationaleResponse.cs
These changes are needed to align the academy conversion rationale response properties with changes made to the rationale property names in the object that the api response deserialises to in the A2B service.
> Update rationale property names in academy conversion response

- TramsDataApi/RequestModels/AcademyTransferProjectFeaturesRequest.cs
AT Projects -> Features -> RddOrEsfaIntervention has been made nullable
When integrating with the API, I found that doing a project update required this to be set to `false` otherwise it would return bad request.
Setting this to false however means that it looks like our users have inputted this data (it's a Yes/No radio button), which means that it falsely marks the section as "in progress" with the user having selected "No"
This update just makes the field nullable to avoid this needing to be set
> Make RddOrEsfaIntervention nullable for AT Requests

- TramsDataApi.Test/Controllers/TrustsControllerTests.cs
- TramsDataApi.Test/Integration/TrustsIntegrationTests.cs
- TramsDataApi.Test/UseCases/SearchTrustsTests.cs
- TramsDataApi/Controllers/TrustsController.cs
- TramsDataApi/Gateways/ITrustGateway.cs
- TramsDataApi/Gateways/TrustGateway.cs
- TramsDataApi/UseCases/ISearchTrusts.cs
- TramsDataApi/UseCases/SearchTrusts.cs
This PR adds simple pagination to the index trusts endpoint.
Also I have make the index trust gateway return trusts ordered by GroupUID. 
This is mainly for testability as GroupUID is stored in the DB as a string and ordering wont work nicely without some tomfoolery.
> Add pagination to index trusts

- TramsDataApi.Test/Factories/AcademyConversionProjectFactoryTests.cs
- TramsDataApi.Test/Factories/AcademyConversionProjectResponseFactoryTests.cs
- TramsDataApi.Test/Integration/AcademyConversionProjectsIntegrationTests.cs
- TramsDataApi/Factories/AcademyConversionProjectFactory.cs
- TramsDataApi/Factories/AcademyConversionProjectResponseFactory.cs
- Map the `RevenueCarryForwardAtEndMarchCurrentYear` and `ProjectedRevenueBalanceAtEndMarchNextYear` to their corresponding fields in the `IfdPipeline` table when retrieving and updating.
- Map the `CapitalCarryForwardAtEndMarchCurrentYear`, `CapitalCarryForwardAtEndMarchNextYear`, `SchoolBudgetAdditionalInformation` and `SchoolBudgetInformationSectionComplete` fields to their corresponding fields in the `AcademyConversionProject` table as they don't have existing corresponding fields in the sip database.
- Set School budget decimal fields to null if they're set to `default(decimal)` when updating.
> Map school budget information fields when updating

- TramsDataApi.Test/Integration/AcademyConversionProjectNotesIntegrationTests.cs
- TramsDataApi/TramsDataApi.csproj
- TramsDataApi/UseCases/AddAcademyConversionProjectNote.cs
There was a bug with the project note date (the date at which the project note is created) whereby on the dev environment the `Date` field value was displaying as one-hour behind but was displaying correctly when running locally.
I assume this is because the server where the code is hosted thinks `DateTime.Now` is equivalent to GMT time, whereas my machine thinks `DateTime.Now` is equivalent to GMT + 1 (BST). 
Therefore I've changed it so that when the project note date is created, the UTC time is got and then converted to london's local time. 
This requires the time zone id, however, different operating systems use different values for the id of the same time zone (e.g. linux uses `Europe/London` and windows uses `GMT Standard Time` - the latter of which I find misleading because, …
> Ensure project note date is set correctly regardless of where code is hosted

- TramsDataApi.Test/Integration/TrustsIntegrationTests.cs
- TramsDataApi.Test/TramsDataApiFactory.cs
- TramsDataApi/Gateways/TrustGateway.cs
**Add a Fuzzy Search feature to when searching Trusts by Group Name.**
1. Update the SearchGroups() method in the TrustGateway to include Contains()
2. Add new Integration Test to check for when searching by just a partial GroupName
3. Add new Integration Test to check for when searching by all parameters and a partial GroupName
> Add fuzzy search

- TramsDataApi.Test/Integration/EducationPerformanceIntegrationTests.cs
- TramsDataApi.Test/UseCases/GetKeyStagePerformanceByUrnTests.cs
- TramsDataApi/DatabaseModels/LegacyTramsDbContext.EducationPerformanceData.cs
- TramsDataApi/DatabaseModels/SipEducationalperformancedata.cs
- TramsDataApi/Factories/EducationPerformanceFactories/GroupedEducationPerformanceFactory.cs
- TramsDataApi/Factories/EducationPerformanceFactories/KeyStage5PerformanceResponseFactory.cs
- TramsDataApi/ResponseModels/EducationalPerformance/EducationalPerformanceResponse.cs
- TramsDataApi/ResponseModels/EducationalPerformance/KeyStage5PerformanceResponse.cs
- TramsDataApi/UseCases/GetKeyStagePerformanceByUrn.cs
This PR adds the keystage 5 data that we currently store in TRAMS db.
> Add keystage 5 response data and update tests

- TramsDataApi.Test/Factories/EstablishmentResponseFactoryTests.cs
- TramsDataApi.Test/Integration/EstablishmentsIntegrationTests.cs
- TramsDataApi.Test/Integration/TrustsIntegrationTests.cs
- TramsDataApi.Test/UseCases/GetEstablishmentByUkprnTests.cs
- TramsDataApi.Test/UseCases/GetEstablishmentsByTrustUidTests.cs
- TramsDataApi/Factories/EstablishmentResponseFactory.cs
- TramsDataApi/Factories/FurtherEducationEstablishmentResponseFactory.cs
- TramsDataApi/Gateways/EstablishmentGateway.cs
- TramsDataApi/Gateways/IEstablishmentGateway.cs
- TramsDataApi/ResponseModels/ProviderResponse.cs
- TramsDataApi/UseCases/GetEstablishment.cs
- TramsDataApi/UseCases/GetEstablishmentsByTrustUid.cs
**Issue**
When attempting to get data from a Further Education Establishment, the `MisEstablishment` field comes back as null because a Further Education Establishment does not exist in the `Mis.Establishments` table. However, they do exist in the `Mis.FurtherEducationEstablishments` table.
At present the `MISFurtherEducationEstablishment` property in the response is set to null. Instead it needs to make its own call to the database to bring back a more appropriate result.
**Solution**
Build out a new vertical slice that interacts with the `Mis.FurtherEducationEstablishments` table and utilize the existing `FurtherEducationEstablishments` DatabaseModel and the existing `MISFEAResponse`. 
**Approach**
1. Update the existing EstablishmentResponseFactory to take a …
> 70670: MisEstablishment returning null for Further Education Establishments

- TramsDataApi.Test/Integration/EducationPerformanceIntegrationTests.cs
- TramsDataApi.Test/UseCases/GetKeyStagePerformanceByUrnTests.cs
- TramsDataApi/DatabaseModels/Account.cs
- TramsDataApi/DatabaseModels/LegacyTramsDbContext.EducationPerformanceData.cs
- TramsDataApi/DatabaseModels/LegacyTramsDbContext.cs
- TramsDataApi/DatabaseModels/SipEducationalperformancedata.cs
- TramsDataApi/Gateways/EducationPerformanceGateway.cs
- TramsDataApi/Gateways/IEducationPerformanceGateway.cs
- TramsDataApi/UseCases/GetKeyStagePerformanceByUrn.cs
This PR adds a check to ensure that the Local authority performance data is for the Local Authority for the requested academy.
> Add check for account's local authority when getting education performance data

- TramsDataApi.Test/Factories/AcademyConversionProjectFactoryTests.cs
- TramsDataApi.Test/Factories/AcademyConversionProjectResponseFactoryTests.cs
- TramsDataApi.Test/Integration/AcademyConversionProjectsIntegrationTests.cs
- TramsDataApi/DatabaseModels/AcademyConversionProject.cs
- TramsDataApi/Factories/AcademyConversionProjectFactory.cs
- TramsDataApi/Factories/AcademyConversionProjectResponseFactory.cs
- TramsDataApi/Migrations/TramsDb/20210722160223_AddPrevHtbDateQuestionFieldToACP.Designer.cs
- TramsDataApi/Migrations/TramsDb/20210722160223_AddPrevHtbDateQuestionFieldToACP.cs
- TramsDataApi/RequestModels/AcademyConversionProject/UpdateAcademyConversionProjectRequest.cs
- TramsDataApi/ResponseModels/AcademyConversionProject/AcademyConversionProjectResponse.cs
- Add new field `PreviousHeadTeacherBoardDateQuestion` to `AcademyConversionProject` table
- Map `PreviousHeadTeacherBoard` field in ACP update route
- Map `PreviousHeadTeacherBoardDateQuestion` field in ACP get and patch routes
> Map previous head teacher board fields when updating and retrieving ACP

- TramsDataApi.Test/Integration/TrustsIntegrationTests.cs
- TramsDataApi.Test/UseCases/SearchTrustsTests.cs
- TramsDataApi/Gateways/TrustGateway.cs
Update `TrustGateway` to check the Group Type contains the word 'trust'. There are 3 diffferent types of trust in the Group table:
1. Single-academy trust
2. Multi-academy trust
3. Trust
The `TrustIntegrationTests `have also been updated to ensure a `GroupType `is set when using `Builder `on the `Groups`.
> Add conditional to check GroupType is Trust

- TramsDataApi.ApplyToBecome/SyncAcademyConversionProject.cs
- TramsDataApi.Test/Factories/AcademyConversionProjectFactoryTests.cs
- TramsDataApi.Test/Factories/AcademyConversionProjectResponseFactoryTests.cs
- TramsDataApi.Test/Integration/AcademyConversionProjectsIntegrationTests.cs
- TramsDataApi/DatabaseModels/AcademyConversionProject.cs
- TramsDataApi/Factories/AcademyConversionProjectFactory.cs
- TramsDataApi/Factories/AcademyConversionProjectResponseFactory.cs
- TramsDataApi/Migrations/TramsDb/20210810072617_AddKS4AdditionalInfoToACP.Designer.cs
- TramsDataApi/Migrations/TramsDb/20210810072617_AddKS4AdditionalInfoToACP.cs
- TramsDataApi/RequestModels/AcademyConversionProject/UpdateAcademyConversionProjectRequest.cs
- TramsDataApi/ResponseModels/AcademyConversionProject/AcademyConversionProjectResponse.cs
- Rename KS2 additional info field in ACP db table to be more specific
- Add KS4 additional info field to ACP table
- Map KS4 additional info field when retrieving and updating ACP
> KS4 additional info

- TramsDataApi.Test/Factories/KeyStage4ResponseFactoryTests.cs
- TramsDataApi.Test/Integration/EducationPerformanceIntegrationTests.cs
- TramsDataApi.Test/UseCases/GetKeyStagePerformanceByUrnTests.cs
- TramsDataApi/DatabaseModels/LegacyTramsDbContext.EducationPerformanceData.cs
- TramsDataApi/DatabaseModels/SipEducationalperformancedata.cs
- TramsDataApi/Factories/EducationPerformanceFactories/GroupedEducationPerformanceFactory.cs
- TramsDataApi/Factories/EducationPerformanceFactories/KeyStage4PerformanceResponseFactory.cs
- TramsDataApi/ResponseModels/EducationalPerformance/KeyStage4PerformanceResponse.cs
The PR adds the following fields to the educationPerformance db object and response:
- SipEnteringEbacc
- SipEnteringEbaccEngland (National average)
- SipEnteringEbaccLocalAuthorityAverage (Local authority Average)
> Add entering ebacc ks4 data

- TramsDataApi.Test/Factories/KeyStage4ResponseFactoryTests.cs
- TramsDataApi.Test/Integration/EducationPerformanceIntegrationTests.cs
- TramsDataApi.Test/UseCases/GetKeyStagePerformanceByUrnTests.cs
- TramsDataApi/Factories/EducationPerformanceFactories/KeyStage4PerformanceResponseFactory.cs
This PR updated the national and local authority Ebacc averages to use the `EnteringEbacc` field.
> Change la and national fields to use entering ebacc field

- TramsDataApi.Test/Integration/EducationPerformanceIntegrationTests.cs
- TramsDataApi.Test/UseCases/GetKeyStagePerformanceByUrnTests.cs
- TramsDataApi/DatabaseModels/LegacyTramsDbContext.EducationPerformanceData.cs
- TramsDataApi/DatabaseModels/SipEducationalperformancedata.cs
- TramsDataApi/Factories/EducationPerformanceFactories/GroupedEducationPerformanceFactory.cs
- TramsDataApi/Factories/EducationPerformanceFactories/KeyStage5PerformanceResponseFactory.cs
- TramsDataApi/ResponseModels/EducationalPerformance/KeyStage5PerformanceResponse.cs
This PR adds the data for:
- AppliedGeneral Progress
- Academic Progress
to the ks5 object and api response.
> Add applied general and academy progress data to ks5

- TramsDataApi.Test/Controllers/AcademyConversionProjectsControllerV2Tests.cs
- TramsDataApi.Test/Factories/PagingResponseFactoryTests.cs
- TramsDataApi.Test/Integration/AcademyConversionProjectsIntegrationTests.cs
- TramsDataApi.Test/UseCases/GetAcademyConversionProjectsTests.cs
- TramsDataApi/Controllers/V2/AcademyConversionProjectController.cs
- TramsDataApi/Gateways/IIfdPipelineGateway.cs
- TramsDataApi/Gateways/IfdPipelineGateway.cs
- TramsDataApi/ResponseModels/PagingResponseFactory.cs
- TramsDataApi/UseCases/GetAcademyConversionProjects.cs
Update paging response factory to use the VirtualPath as path base is now default populated with string.empty and request.path always returns localhost
> Fix - Paging Response and ProjectStatus when search without state on V2 Controller

- TramsDataApi.Test/Factories/AcademyConversionProjectFactoryTests.cs
- TramsDataApi/Factories/AcademyConversionProjectFactory.cs
- TramsDataApi/RequestModels/AcademyConversionProject/UpdateAcademyConversionProjectRequest.cs
Conversion grant fields were being updated when given null - this updates the request object/factory to support patching and only update when given data
> Support patching conversion grant fields

- TramsDataApi.Test/Factories/AcademyTransferProjectFactoryTests.cs
- TramsDataApi/Factories/AcademyTransferProjectFactory.cs
- TramsDataApi/RequestModels/AcademyTransferProjectDatesRequest.cs
This PR is to allow the dates used in academy transfers to be reset back to null after they have previously been populated.
> Allow dates to be updated to null

- TramsDataApi/Controllers/V2/TrustsController.cs
In this PR I updated the `trusts/{ukprn}` endpoint to be singular `trust/{ukprn}` to be consistent with the other v1 endpoints.
> Update v2 trust endpoint naming to be consistent with v1 endpoints

- TramsDataApi.Test/Controllers/ConcernsCaseControllerTests.cs
- TramsDataApi.Test/Integration/ConcernsIntegrationTests.cs
- TramsDataApi/Controllers/V2/ConcernsCaseController.cs
- TramsDataApi/Controllers/V2/ConcernsRecordController.cs
- TramsDataApi/ResponseModels/ApiResponseV2.cs
- TramsDataApi/ResponseModels/ApiSingleResponseV2.cs
In this PR:
- Add`ApiSingleResponseV2` response object to use when we need to return a single object
> Add single object v2 response

- TramsDataApi.Test/Factories/EstablishmentResponseFactoryTests.cs
- TramsDataApi.Test/Integration/TrustsIntegrationTests.cs
- TramsDataApi/DatabaseModels/Establishment.cs
- TramsDataApi/DatabaseModels/LegacyTramsDbContext.cs
- TramsDataApi/Factories/EstablishmentResponseFactory.cs
Removes depreciated table column from GIAS establishment as it has ben removed from the database and pipelines.
> Remove depreciated table column from gias establishment

- TramsDataApi.Test/Controllers/TrustsControllerV2Tests.cs
- TramsDataApi/Controllers/V2/ConcernsCaseController.cs
- TramsDataApi/Controllers/V2/ConcernsRecordController.cs
- TramsDataApi/Controllers/V2/TrustsController.cs
Update v2 controllers to use the single response object for single response endpoints
> Update v2 controllers to use the single response

- TramsDataApi.Test/Controllers/ConcernsCaseControllerTests.cs
- TramsDataApi.Test/Integration/ConcernsIntegrationTests.cs
- TramsDataApi.Test/UseCases/UpdateConcernsCaseTests.cs
- TramsDataApi/Controllers/V2/ConcernsCaseController.cs
- TramsDataApi/Factories/ConcernsCaseFactory.cs
- TramsDataApi/Gateways/ConcernsCaseGateway.cs
- TramsDataApi/Gateways/IConcernsCaseGateway.cs
- TramsDataApi/Startup.cs
- TramsDataApi/UseCases/IUpdateConcernsCase.cs
- TramsDataApi/UseCases/UpdateConcernsCase.cs
In this PR:
- Add the `UpdateConcernsCase` usecase
- Add the PATCH `concerns-cases/{urn}` endpoint to update concerns cases.
- Add the Update method in `ConcernsCaseFactory` to update an existing Concerns Case object using data from request.
- Add Update function on the Concerns Case Gateway to update and save the updated data.
> Add PATCH update route for Concerns Cases

- TramsDataApi.Test/Factories/ConcernsTypeResponseFactoryTests.cs
- TramsDataApi.Test/Integration/ConcernsIntegrationTests.cs
- TramsDataApi.Test/UseCases/IndexConcernsTypesTests.cs
- TramsDataApi/Controllers/V2/ConcernsStatusController.cs
- TramsDataApi/Controllers/V2/ConcernsTypeController.cs
- TramsDataApi/Factories/ConcernsTypeResponseFactory.cs
- TramsDataApi/Gateways/ConcernsTypeGateway.cs
- TramsDataApi/Gateways/IConcernsTypeGateway.cs
- TramsDataApi/ResponseModels/ConcernsTypeResponse.cs
- TramsDataApi/Startup.cs
- TramsDataApi/UseCases/IIndexConcernsTypes.cs
- TramsDataApi/UseCases/IndexConcernsTypes.cs
This PR adds the GET route `concerns-types` to get all concern type objects.
> Add get concerns types route

- TramsDataApi/DatabaseModels/TramsDbContext.cs
- TramsDataApi/Migrations/TramsDb/20211119100948_UpdateConcernsUpdatedCreatedAtFieldsMigration.Designer.cs
- TramsDataApi/Migrations/TramsDb/20211119100948_UpdateConcernsUpdatedCreatedAtFieldsMigration.cs
In this PR:
- Update the concerns db models to make the created and updated at fields stop updating in every db migrations
> Update concerns db object createdat and updatedat fields

- TramsDataApi.Test/Integration/ConcernsIntegrationTests.cs
- TramsDataApi.Test/UseCases/GetConcernsRecordsByCaseUrnTests.cs
- TramsDataApi/Controllers/V2/ConcernsRecordController.cs
- TramsDataApi/Gateways/ConcernsCaseGateway.cs
- TramsDataApi/Gateways/IConcernsCaseGateway.cs
- TramsDataApi/Startup.cs
- TramsDataApi/UseCases/GetConcernsRecordsByCaseUrn.cs
- TramsDataApi/UseCases/IGetConcernsRecordsByCaseUrn.cs
In this PR:
- Add the `concerns-records/case/urn/{urn}` route to get concerns records by case urn.
- Add `GetConcernsCaseIncludingRecordsByUrn` gateway method to eager load records and record data when getting a concerns case.
- Add usecase to get concerns records by case urn
> Add get concerns records by case urn

- TramsDataApi.Test/Controllers/A2BApplicationController.cs
- TramsDataApi.Test/Factories/A2BApplicationFactoryTests.cs
- TramsDataApi.Test/Factories/A2BApplicationResponseFactoryTests.cs
- TramsDataApi.Test/Integration/ApplyToBecomeIntegrationTests.cs
- TramsDataApi.Test/UseCases/CreateA2BApplicationTests.cs
- TramsDataApi.Test/UseCases/GetA2BApplicationTests.cs
- TramsDataApi/Controllers/V2/A2BApplicationController.cs
- TramsDataApi/DatabaseModels/A2BApplication.cs
- TramsDataApi/Factories/A2BApplicationFactory.cs
- TramsDataApi/Factories/A2BApplicationResponseFactory.cs
- TramsDataApi/Gateways/A2BApplicationGateway.cs
- TramsDataApi/Gateways/IA2BApplicationGateway.cs
- TramsDataApi/Migrations/TramsDb/20211122170608_AddDbGeneratedIdColumnToA2BApplication.Designer.cs
- TramsDataApi/Migrations/TramsDb/20211122170608_AddDbGeneratedIdColumnToA2BApplication.cs
- TramsDataApi/RequestModels/ApplyToBecome/A2BApplicationByIdRequest.cs
- TramsDataApi/RequestModels/ApplyToBecome/A2BApplicationCreateRequest.cs
- TramsDataApi/ResponseModels/ApplyToBecome/A2BApplicationResponse.cs
- TramsDataApi/Startup.cs
- TramsDataApi/UseCases/CreateA2BApplication.cs
- TramsDataApi/UseCases/GetA2BApplication.cs
- TramsDataApi/UseCases/ICreateA2BApplication.cs
- TramsDataApi/UseCases/IGetA2BApplication.cs
In this PR:
Add the `apply-to-become/application/{ApplicationId}` route to get A2B applications by ApplicationId
Add the `apply-to-become/application` POST route to create A2B applications
Add the gateway methods to Create / Retrieve applications
Add the use case to get A2B applications by Application Id
Add the use case to create A2B Applications from request
Add Factory methods to create the associated models for Create / Retrieve applications
Add Migration to change table `sdd.A2BApplication` to an identity column
Add Associated unit / integration tests for the changes detailed above
> A2b create get post endpoints for application

- TramsDataApi.Test/Controllers/A2BApplicationControllerTests.cs
- TramsDataApi.Test/Controllers/A2BApplicationKeyPersonsControllerTests.cs
- TramsDataApi.Test/UseCases/GetA2BApplicationKeyPersonsTests.cs
- TramsDataApi.Test/UseCases/GetA2BApplicationTests.cs
- TramsDataApi/Controllers/V2/A2BApplicationController.cs
- TramsDataApi/Controllers/V2/A2BApplicationKeyPersonsController.cs
- TramsDataApi/RequestModels/ApplyToBecome/A2BApplicationByIdRequest.cs
- TramsDataApi/RequestModels/ApplyToBecome/A2BApplicationKeyPersonsByIdRequest.cs
- TramsDataApi/UseCases/GetA2BApplication.cs
- TramsDataApi/UseCases/GetA2BApplicationKeyPersons.cs
- TramsDataApi/UseCases/IGetA2BApplication.cs
- TramsDataApi/UseCases/IGetA2BApplicationKeyPersons.cs
Delete A2BApplicationByIdRequest.cs and A2BApplicationKeyPersonsByIdRequest
Adjust code to use int Id rather than request model
> Remove unneeded request models from A2BApplication and A2BApplicationKeyPersons

- TramsDataApi.Test/Factories/AcademyTransferProjectFactoryTests.cs
- TramsDataApi.Test/Factories/AcademyTransferProjectResponseFactoryTests.cs
- TramsDataApi.Test/Integration/AcademyTransferProjectIntegrationTests.cs
- TramsDataApi.Test/UseCases/IndexAcademyTransferProjectTests.cs
- TramsDataApi/DatabaseModels/TransferringAcademies.cs
- TramsDataApi/Factories/AcademyTransferProjectFactory.cs
- TramsDataApi/Factories/AcademyTransferProjectResponseFactory.cs
- TramsDataApi/Migrations/TramsDb/20220218144346_AdditionalInformationPerAcademy.Designer.cs
- TramsDataApi/Migrations/TramsDb/20220218144346_AdditionalInformationPerAcademy.cs
- TramsDataApi/RequestModels/TransferringAcademiesRequest.cs
- TramsDataApi/ResponseModels/TransferringAcademiesResponse.cs
- TramsDataApi/UseCases/IndexAcademyTransferProjects.cs
Add additional information fields to the Academies level.
POST, PATCH and GET updated with the new fields
Data copied to academy level from project (Project additional information can be removed post Transfers deployment)
> Feature/87756 add additional information fields for Academy Transfers

- CypressTests/cypress/integration/academytransfers/academyTransferE2E.js
The Cypress test: **E2E Academy Transfers**
Was using hard coded data.
So no it records the original data, changes it, then changes it back to the original.
So even if data is missing at first, it will assert that there is missing data, add some, then remove it again so it's back to it's original state.
> Updated Academy E2E tests

- CypressTests/cypress/integration/conversions/89770_api_apply-to-become/89785_schemaJson.js
- API changes made now  return data body 'null', and no longer reflects current json schema type format, : pending on fix
- To unskip once fix has been implemented
> Skip json schema tests

- TramsDataApi.Test/Factories/AcademyTransferProjectFactoryTests.cs
- TramsDataApi.Test/Factories/AcademyTransferProjectResponseFactoryTests.cs
- TramsDataApi/DatabaseModels/AcademyTransferProjects.cs
- TramsDataApi/Factories/AcademyTransferProjectFactory.cs
- TramsDataApi/Factories/AcademyTransferProjectResponseFactory.cs
- TramsDataApi/Migrations/TramsDb/20220511110620_RemoveRedundantColumnsForTransfers.Designer.cs
- TramsDataApi/Migrations/TramsDb/20220511110620_RemoveRedundantColumnsForTransfers.cs
- TramsDataApi/Migrations/TramsDb/20220511142948_RemoveRedundantColumnAcademyPerformanceForTransfers.Designer.cs
- TramsDataApi/Migrations/TramsDb/20220511142948_RemoveRedundantColumnAcademyPerformanceForTransfers.cs
Missed other redundant column Academy Performance. This is not used in Academy Transfers.
All data in the column in Production is NULL
> Feature/87757 remove redundant columns AB#87757

- TramsDataApi.Test/Controllers/SRMAControllerTests.cs
- TramsDataApi.Test/Factories/SRMAFactoryTests.cs
- TramsDataApi.Test/UseCases/GetSRMAsByCaseIdTests.cs
- TramsDataApi/Controllers/V2/SRMAController.cs
- TramsDataApi/DatabaseModels/SRMACase.cs
- TramsDataApi/Factories/CaseActionFactories/SRMAFactory.cs
- TramsDataApi/Gateways/SRMAGateway.cs
- TramsDataApi/Migrations/TramsDb/20220531151943_Change_caseID_to_CaseURN.Designer.cs
- TramsDataApi/Migrations/TramsDb/20220531151943_Change_caseID_to_CaseURN.cs
- TramsDataApi/RequestModels/CaseActions/SRMA/CreateSRMARequest.cs
- TramsDataApi/ResponseModels/CaseActions/SRMA/SRMAResponse.cs
What is the change?
Changed SRMA to case reference, from case id to case URN
Why do we need the change?
The initial implementation followed the database design but the front end (concerns casework) and the rest of the system use URN to identify cases.
What is the impact?
Localised impact on previous SRMA development 
Azure DevOps Ticket
94850
> Changed SRMA to case reference, from case id to case URN

- TramsDataApi/Migrations/TramsDb/20220218144346_AdditionalInformationPerAcademy.cs
Added the EXEC function to work around parser error in a previous migration script (occurs because referenced columns don't currently exist on the table.)
> fix a migration script now that table columns are removed

- .github/workflows/test.yml
Adding the dotnet-coverage tool to the build & test workflow. This allows us to collect code coverage results and report them back into SonarCloud.
> Add dotnet-coverage to testing to collect coverage for sonarcloud

- .github/workflows/test.yml
Until we can figure out how to stop dotnet-coverage from suppressing test failures, removing from the sonar scanning
> Remove dotnet-coverage from test step to stop silent failures

- TramsDataApi/Controllers/AcademyTransferProjectController.cs
- TramsDataApi/UseCases/SearchAcademyTransferProjects.cs
This isn't actually a V2 endpoint so the `ApiResponseV2` is replaced with the simpler `PagedResult`.
> Change return type as the endpoint is a V1 endpoint.

- .github/workflows/test.yml
~Uses dotCover to collect test coverage results to pipe to SonarCloud.
If unit tests are failing, the build will now fail with this command - see example [here](https://github.com/DFE-Digital/academies-academisation-api/actions/runs/3384728750)~
Uses default dotnet test functionality to collect test results and outputs it to generic test coverage data for SonarCloud using [ReportGenerator](https://reportgenerator.io/)
> Use dotnet test for coverage collection, reportgenerator to output to sonarcloud

- TramsDataApi.Test/Controllers/EstablishmentsControllerTests.cs
- TramsDataApi.Test/Integration/EstablishmentsIntegrationTests.cs
- TramsDataApi.Test/UseCases/GetEstablishmentsByUrnsTests.cs
- TramsDataApi/Controllers/EstablishmentsController.cs
- TramsDataApi/Gateways/EstablishmentGateway.cs
- TramsDataApi/Gateways/IEstablishmentGateway.cs
- TramsDataApi/RequestModels/GetEstablishmentsByUrnsRequest.cs
- TramsDataApi/Startup.cs
- TramsDataApi/UseCases/GetEstablishmentsByUrns.cs
- TramsDataApi/UseCases/IGetEstablishmentsByUrns.cs
Currently, in the Complete application, we fetch establishment data for each
project on our project index page as a separate API request. This is at times
very slow, and while we have explored various options to speed this up in the
client, we think adding a `bulk` endpoint to the API may be the better choice.
This adds a use case for getting establishments by a list of URNs. 
So that we aren't performing a database query for each related piece of data
per URN (`MisEstablishments`, `FurtherEducationEstablishments` etc.), this also
adds Gateway methods to fetch each by a list of URNs.
This adds a `bulk` endpoint in the format
`/establishments/bulk?Urn=12345&Urn=23456"` so that multiple establishments can
be retrieved in a single request.
There is no standard for the correct way to pass …
> Get bulk establishments

- TramsDataApi.Test/Integration/EstablishmentsIntegrationTests.cs
We clean up the test database for the Establishments integration tests in the `Dispose` method.
Currently, we aren't removing the test data from the `FurtherEducationEstablishments` table. This means that when running the tests multiple times, we see a primary key constraint error because we are trying to insert the same test data.
This adds clean up of the `FurtherEducationEstablishments` table to the `Dispose` method so that any test data is removed after every test.
> Fix flaky Establishments integration tests

- TramsDataApi/Controllers/V2/TrustsController.cs
- TramsDataApi/UseCases/SearchTrusts.cs
Changed Trust search execute to use ToArray so that it definitely won't cause any multiple enumerations.
Changed TrustsController to only serialise the results for logging if the debug logging is actually enabled.
> Small perf tweaks to v2 Trust Search 

- terraform/README.md
- terraform/container-apps-hosting.tf
- terraform/locals.tf
- terraform/variables.tf
The default probe path of "/" returns a 401 status code due to a missing API Key. This change adds 3 vars to allow us to override the probe path to the Swagger API homepage which will return a 200 OK
> Add probe path overrides

- terraform/.terraform.lock.hcl
- terraform/README.md
- terraform/container-apps-hosting.tf
- terraform/data.tf
- terraform/key-vault-tfvars-secrets.tf
- terraform/locals.tf
- terraform/variables.tf
What is the change?
Instead of defining all of the terraform for deploying a Key Vault, I have switched to using a terraform module which shifts a lot of the configurable options upstream and reduces the complexity of the terraform code in this repo.
Why do we need the change?
Allows for centralised updates for the Key Vault resource and reduces complexity of the terraform in this repo.
What is the impact?
Applying this terraform change will destroy the existing tfvars Key Vault and recreate it. This has no impact on the running services within Azure and is considered safe/low impact.
> Terraform Key Vault tfvars module

- .github/workflows/continuous-integration-dotnet.yml
Node.js 12 actions are deprecated.
> Update action versions to latest NodeJS package

- TramsDataApi.Test/UseCases/SearchTrustsTests.cs
- TramsDataApi/UseCases/SearchTrusts.cs
**What is the change?**
- Fix issue when returning trust address information via the trusts endpoint . Incorrect field used when filtering trusts linked to a parent group. 
- Added associated test following similar format to existing tests.
**Why do we need the change?**
Ensure address information is returned by the trusts endpoint and can be consumed by other services
**What is the impact?**
Enable Record Concerns to display town within trust search page. The town is displayed to users enabling differentiation between trusts with the same name but in different parts of the country. 
**Azure DevOps Ticket**
https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_boards/board/t/Concerns%20Casework/Stories/?workitem=125531
> Fixed logic for returning trusts and associated address information

- .github/workflows/build-and-push-image.yml
- .github/workflows/security-tests.yml
- CypressTests/docker-compose.yml
Adds capability to run the Cypress tests through ZAP for passive security scanning, including GitHub action to run post-deployment to dev environment.
Files will be uploaded to a [container](https://portal.azure.com/#@platform.education.gov.uk/resource/subscriptions/1d692707-6019-4f8c-b337-ec8cad61f998/resourceGroups/s184d01-rsd-owasp-reports/providers/Microsoft.Storage/storageAccounts/s184d01rsdowaspreports/storagebrowser) on Azure under the directory `<project>/<git-hash>/ZAP-Report.html`.
Reports will always upload, regardless of test failures, as long as the action is not cancelled.
> **Note**
> To read them you will need read access to Azure CIP.
Makes use of a Service Principal account to authenticate to Azure
**Notes**
The following need to be completed before this PR can be …
> Add security tests workflow

- terraform/.terraform.lock.hcl
- terraform/README.md
- terraform/container-apps-hosting.tf
- terraform/locals.tf
- terraform/variables.tf
* Allows specifying the Front Door CDN forwarding protocol
* Allows adding a list of IP addresses allowed to access the Container App
> Bump container apps hosting module to v0.19.1

- CypressTests/cypress/e2e/v1/healthchecks.cy.js
- CypressTests/cypress/e2e/v1/keyStagePerformance.cy.js
- CypressTests/cypress/e2e/v2/baselineTracker.cy.js
- CypressTests/cypress/e2e/v2/fssProjects.cy.js
- CypressTests/cypress/e2e/v3/trusts.cy.js
- CypressTests/cypress/e2e/v4/trusts.cy.js
- CypressTests/cypress/plugins/index.js
- CypressTests/cypress/support/commands.js
- CypressTests/cypress/support/validate-schema-command.js
Adds tests for the following endpoints:
v1
- `keyStagePerformance`
v2
- `baseline-tracker`
v3
- `trusts`
also removes unnecessary `;`s from end of commands to appease eslint and renames files for consistency across tests
> Add legacy Cypress tests for v1, v2 and v3 endpoints

- TramsDataApi.Test/Extensions/StringExtensionsTests.cs
- TramsDataApi.Test/Integration/TrustsV3IntegrationTests.cs
- TramsDataApi/Extensions/StringExtensions.cs
- TramsDataApi/Gateways/TrustGateway.cs
logic for ordering by group uid was wrong, because group uid is a string
converted the string to a number, so the ordering works correctly
added utility method for converting strings to numbers to prove all scenarios would work
https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_workitems/edit/153650
> 153650: trusts missing establishments

- Dfe.Academies.Api.Infrastructure/Repositories/TrustRepository.cs
- Dfe.Academies.Application.Tests/Queries/Trust/TrustQueriesTests.cs
- Dfe.Academies.Application/Trust/ITrustQueries.cs
- Dfe.Academies.Application/Trust/TrustQueries.cs
- Dfe.Academies.Domain/Trust/ITrustRepository.cs
- Dfe.Academies.Domain/Trust/TrustStatus.cs
- TramsDataApi.Test/Integration/V4/TrustV4IntegrationTests.cs
- TramsDataApi/Controllers/V4/TrustsController.cs
- TramsDataApi/Startup.cs
Adds an option to the trust search endpoint to filter to only open trusts or to any trust status.
Default behaviour is retained of only search for open trusts for backwards compatibility, but providing anything other that "Open" will allow you to disable this filter.
> 152436 Allow Trusts that do not have a status of Open to be searched for

- Dockerfile
When the 8.0 monorepo was merged, the SDK was bumped to 8.0 but the runtime was left on 7 which meant the container could not boot because it did not have the correct version.
The jump to 8 also means the base image now sets 8080 as the default so an ENV was added to set back to 80 which should mean the least impact to the container app environment
> Aspnet 8.0

- TramsDataApi/Middleware/ApiKeyMiddleware.cs
Health check monitors need a route that is valid and isn't Swagger UI to test for availability
> Ignore API Key when accessing healthcheck endpoint

- .github/workflows/build-and-push-image.yml
- Prefix image tags when built on GHCR so that persons api is distinct from academies api, otherwise we will have 2x academies-api packages published which are different projects
> Add tag prefix when building multiple images

- Dfe.Academies.PersonsApi.Tests.Integration/Controllers/ConstituenciesControllerTests.cs
- Dfe.Academies.PersonsApi.Tests.Integration/Dfe.Academies.PersonsApi.Tests.Integration.csproj
- Dfe.Academies.PersonsApi.Tests.Integration/Mocks/CustomWebApplicationFactory.cs
- TramsDataApi.sln
Added integration tests for Persons API
> Added integration tests for Persons API

- .github/workflows/docker-build.yml
- .github/workflows/docker-test.yml
This new GitHub Workflow will run on pushes to `main`. It will build and scan Docker images for the Academies API and Persons API, and report any CVE findings in the GitHub Security tab.
> Scan the built docker images for CVEs

- .github/workflows/docker-build.yml
The docker images won't build properly without this flag.
> Fix docker image scan workflow

- Dfe.Academies.Application/Constituencies/Queries/GetMemberOfParliamentByConstituencies/GetMemberOfParliamentByConstituencies.cs
- Tests/Dfe.Academies.Application.Tests/Dfe.Academies.Application.Tests.csproj
- Tests/Dfe.Academies.Application.Tests/QueryHandlers/Constituency/GetMemberOfParliamentByConstituencyQueryHandlerTests.cs
- Tests/Dfe.Academies.Application.Tests/QueryHandlers/Constituency/GetMemberOfParliamentsByConstituenciesQueryHandlerTests.cs
- Tests/Dfe.Academies.Application.Tests/QueryHandlers/Establishment/GetAllPersonsAssociatedWithAcademyByUrnTests.cs
- Tests/Dfe.Academies.Testing.Common/Customizations/AutoMapperCustomization.cs
- Tests/Dfe.Academies.Testing.Common/Customizations/Models/AcademyGovernanceCustomization.cs
- Tests/Dfe.Academies.Testing.Common/Customizations/Models/MemberOfParliamentCustomization.cs
- Tests/Dfe.Academies.Testing.Common/Customizations/OmitCircularReferenceCustomization.cs
- Tests/Dfe.Academies.Testing.Common/Dfe.Academies.Testing.Common.csproj
> Improving unit tests

- Dfe.Academies.Application/Common/Exceptions/CustomProblemDetails.cs
- Dfe.Academies.Application/Common/Models/Result.cs
- Dfe.Academies.Application/Constituencies/Queries/GetMemberOfParliamentByConstituencies/GetMemberOfParliamentByConstituencies.cs
- Dfe.Academies.Application/Constituencies/Queries/GetMemberOfParliamentByConstituency/GetMemberOfParliamentByConstituency.cs
- Dfe.Academies.Application/Establishment/Queries/GetAllPersonsAssociatedWithAcademyByUrn/GetAllPersonsAssociatedWithAcademyByUrn.cs
- Dfe.Academies.Application/Establishment/Queries/GetMemberOfParliamentBySchool/GetMemberOfParliamentBySchool.cs
- Dfe.Academies.Application/Establishment/Queries/GetMemberOfParliamentBySchool/GetMemberOfParliamentBySchoolValidator.cs
- Dfe.Academies.Application/Trust/Queries/GetAllPersonsAssociatedWithTrustByTrnOrUkprn/GetAllPersonsAssociatedWithTrustByTrnOrUkprn.cs
- Dfe.PersonsApi.Client/Generated/Client.g.cs
- Dfe.PersonsApi.Client/Generated/Contracts.g.cs
- Dfe.PersonsApi.Client/Generated/swagger.json
- PersonsApi/Controllers/ConstituenciesController.cs
- PersonsApi/Controllers/EstablishmentsController.cs
- PersonsApi/Controllers/TrustsController.cs
- PersonsApi/Middleware/ExceptionHandlerMiddleware.cs
- Tests/Dfe.Academies.Application.Tests/QueryHandlers/Constituency/GetMemberOfParliamentByConstituencyQueryHandlerTests.cs
- Tests/Dfe.Academies.Application.Tests/QueryHandlers/Constituency/GetMemberOfParliamentsByConstituenciesQueryHandlerTests.cs
- Tests/Dfe.Academies.Application.Tests/QueryHandlers/Establishment/GetAllPersonsAssociatedWithAcademyByUrnQueryHandlerTests.cs
- Tests/Dfe.Academies.Application.Tests/QueryHandlers/Establishment/GetMemberOfParliamentBySchoolQueryHandlerTests.cs
- Tests/Dfe.Academies.Application.Tests/QueryHandlers/Trust/GetAllPersonsAssociatedWithTrustByTrnOrUkprnTests.cs
- Tests/Dfe.Academies.PersonsApi.Tests.Integration/Controllers/ConstituenciesControllerTests.cs
- Tests/Dfe.Academies.PersonsApi.Tests.Integration/Controllers/EstablishmentsControllerTests.cs
- Tests/Dfe.Academies.PersonsApi.Tests.Integration/Controllers/TrustsControllerTests.cs
- Tests/Dfe.Academies.Tests.Common/Customizations/CustomWebApplicationDbContextFactoryCustomization.cs
- Tests/Dfe.Academies.Tests.Common/Dfe.Academies.Tests.Common.csproj
> Added New Endpoint GetMPBySchoolURN

- TramsDataApi/Controllers/HealthCheckController.cs
Our HTTP availability test has been switched to 'HEAD' instead of 'GET' but the Academies API doesn't bind requests for this type.
> Add hint to accept HTTP HEAD on health routes

- .github/workflows/build-and-push-package.yml
- Dfe.Academies.Application/MappingProfiles/AcademyWithGovernanceProfile.cs
- Tests/Dfe.Academies.PersonsApi.Tests.Integration/Controllers/ConstituenciesControllerTests.cs
- Tests/Dfe.Academies.PersonsApi.Tests.Integration/Controllers/EstablishmentsControllerTests.cs
- Tests/Dfe.Academies.PersonsApi.Tests.Integration/Controllers/TrustsControllerTests.cs
- Tests/Dfe.Academies.Tests.Common/Customizations/CustomWebApplicationDbContextFactoryCustomization.cs
- Tests/Dfe.Academies.Tests.Common/Dfe.Academies.Tests.Common.csproj
- Tests/Dfe.Academies.Tests.Common/Seeders/MopContextSeeder.cs
- Tests/Dfe.Academies.Tests.Common/Seeders/MstrContextSeeder.cs
Updated Testing logic and packages
> Updated Testing logic and packages

- Dockerfile
- Dockerfile.PersonsApi
* Reduces the overall final image size by using Azure Linux
* Offers maximum compatibility with Azure infrastructure
* Uses arbitrary user instead of 'root'
* Supported by Microsoft
https://github.com/dotnet/dotnet-docker/blob/main/documentation/azurelinux.md#azure-linux
>[!WARNING]
>Note: ASP.NET Core apps (in official images) listen to [port 8080 by default⁠](https://github.com/dotnet/dotnet-docker/blob/6da64f31944bb16ecde5495b6a53fc170fbe100d/src/runtime-deps/8.0/bookworm-slim/amd64/Dockerfile#L7), starting with .NET 8. This is because it is using an arbitrary user. As a result we will need to update the Container App definition to list to Port 8080
> Use Azure Linux base image

- CypressTests/cypress/e2e/v1/healthchecks.cy.js
In https://github.com/DFE-Digital/academies-api/pull/648 we adjusted how health checks work, so that rather than being a registered API Endpoint, it is using the default .NET method, which now also includes a check of the database connection.
The URL is still /HealthCheck but the response body has changed so the cypress test should reflect that.
The /check_db no longer exists as it is part of the /HealthCheck system now.
> Adjust expected response from HealthCheck test

- .github/workflows/build-and-push-image.yml
* This makes it easier for us to manage the individual docker stages for both the main api and the init container
> Split workflow into concurrent build and import stages

- .github/workflows/cypress-tests.yml
- .gitignore
- CypressTests/cypress.config.js
- CypressTests/cypress.env.json
- CypressTests/package-lock.json
- CypressTests/package.json
Added Cypress slack and reporting gubbins into Trams here
> Test get trams api slack reporter ready

- Dfe.Academies.Api.Infrastructure/Repositories/EstablishmentRepository.cs
- Dfe.Academies.Application/Establishment/EstablishmentQueries.cs
- Dfe.Academies.Application/Establishment/IEstablishmentQueries.cs
- Dfe.Academies.Domain/Interfaces/Repositories/IEstablishmentRepository.cs
- Dfe.Academies.TramsDataApi.Tests.Integration/Controllers/V4/EstablishmentsControllerTests.cs
- Dfe.AcademiesApi.Client/Generated/Client.g.cs
- Dfe.AcademiesApi.Client/Generated/Contracts.g.cs
- Dfe.AcademiesApi.Client/Generated/swagger.json
- Tests/Dfe.Academies.Application.Tests/Queries/Establishment/EstablishmentQueriesTests.cs
- Tests/Dfe.Academies.Tests.Common/Customizations/CustomWebApplicationDbContextFactoryCustomization.cs
- Tests/Dfe.Academies.Tests.Common/Seeders/MstrContextSeeder.cs
- TramsDataApi/Controllers/V4/EstablishmentsController.cs
- added optional parameter to the v4 establishments search, this is a non breaking change and should not affect any consumers of the endpoint. It has been added because the autocomplete in various services is showing closed schools/academies and is resulting in users adding the wrong schools to the system.
> Added excludeClosed parameter to v4 search for establishments

- .github/workflows/continuous-integration-dotnet.yml
This forms part of the work to make Sonarqube a mandatory quality gate.
Introducing the `sonar.qualitygate.wait=true` parameter ensures that the scanner will wait for the report to be generated and will fail the workflow if the gate is red, rather than completing the workflow regardless of the gate
> Wait for quality gate response from Sonar before finishing the workflow

- Dfe.Academies.Api.Infrastructure/Repositories/EstablishmentRepository.cs
- Dfe.AcademiesApi.Client/Generated/swagger.json
Replaced SingleOrDefault with FirstOrDefault in the EstablishmentRepository, to avoid exceptions if there is more than one record in the db table.
> Replaced SingleOrDefault with FirstOrDefault
